### ISSUE TITLE
🚀 [Feature Request]: hop count next to short name on the map. 

### ISSUE THREAD

**Issue by meekowai** [meshtastic/Meshtastic-Apple#1000]
### OS

iOS

### Description

Like the title says. I think it would be nice to see hop count on map. If it is direct it can say "0". 
Thanks. 

### Participation

- [ ] I am willing to pay to sponsor this feature.
- [ ] I am willing to submit a pull request for this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
It is on the details of you long press on a node, there is no room on the pin
