### ISSUE TITLE
🚀 [Feature Request]: dropdown for timezone

### ISSUE THREAD

**Issue by meekowai** [meshtastic/Meshtastic-Apple#1009]
### OS

iOS

### Description

Can 'timezone' field be made dropdown with city names like in iOS or windows?
It would be easier than having to type string from [here](https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv)
Thanks. 

### Participation

- [ ] I am willing to pay to sponsor this feature.
- [ ] I am willing to submit a pull request for this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
The string is built automatically based on your location

**Comment by meekowai** [comment]
Mine wasn’t for some reason and have some folks in my mesh with the same problem-time skew -1hr. They have also bad time zone. Having plain names instead of strings would be easier in case installer fails to recognize location.

**Comment by garthvh** [comment]
> Mine wasn’t for some reason and have some folks in my mesh with the same problem-time skew -1hr. They have also bad time zone. Having plain names instead of strings would be easier in case installer fails to recognize location.

If you go under device settings the timezone is automatically populated, all you have to do is save.

**Comment by garthvh** [comment]
It is a ridiculously long list, not suitable for a dropdown

**Comment by meekowai** [comment]
Maybe it can be translated then into gmt+/-hrs, I mean we need to type it in, still easier than the list and long strings. Everyone gets GMT convention. Thanks Garth.
