### ISSUE TITLE
Wisblock unable to enter Network ID and Network Password

### ISSUE THREAD

**Issue by CosmicCEO** [meshtastic/Meshtastic-Apple#1015]
### Firmware Version

2.5.14

### What did you do?

Different screen behavior for Wisblock than HeltecV3 when selecting network (WIFI) mode

### Expected Behavior

Expected - Heltdc V3 I can see toggle for WIFI network, assign a SSID and password when choosing save. A clear outcome is present. 

### Current Behavior

Problem - Wisblock I have only option to select WIFi and save. I presume to lose access to node via BLE. Uncertain outcome. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
There is no wifi on nrf devices
