### ISSUE TITLE
🐞 [Bug]: Connecting to devices with different primary channels mixing up messages in the iOS app

### ISSUE THREAD

**Issue by rdeserm** [meshtastic/Meshtastic-Apple#1017]
### Firmware Version

2.5.15

### What did you do?

I have one device that has the default "LongFast" channel as the primary, so that it reports its position to the public channel.  It has two secondary channels "Family" and "Private". This devices is setup as a permanant outdoor station with high gain antenna.

I have multiple devices that have "Family" as the primary channel, so that I can share precise locations amongst my devices privately.

ISSUE:  When I connect my iOS app to the device with "LongFast" as the primary channel, then disconnect and connect to a device with "Private" as the primary channel.  All the messages that were received in the "LongFast" channel have now overwritten all my "Private" messages in the app

### Expected Behavior

I expect that channel messages stay in their respectivly named channels even if connecting to devices with different channel names as primary

### Current Behavior

"LongFast" primary channel messages showing up in another devices "Private" primary channel when changing connected device in the iOS app

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
Multiple nodes data is not supported

**Comment by garthvh** [comment]
This was fixed by PR #1775 ("Fix data blending when switching between devices"). The root cause — SwiftData records from one device bleeding into another device's view — was addressed by properly scoping all message and channel queries to the currently connected node. The messages should no longer mix up when switching between devices with different primary channels.
