### ISSUE TITLE
Settings / Admin messages to Consider

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#178]
## Some Settings to consider adding

* [x] Reset Node DB
* [ ] Network.IpV4Config [Swift Int To IP](https://medium.com/@aclaytonscott/exploding-ipv4-ranges-using-swift-b7fba6c9ce28)
* [ ] Network.ntpserver
* [x] LoRa.txPower
* [x] LoRa.frequencyOverride
* [ ] Save canned messages module messages when received
* [x] display.flip_screen
* [x] position.gpsEnGpio

## Sections
* [x] Ambient Lighting
* [x] Pax Counter
* [x] Power
~~* [ ] Remote Hardware~~
* [x] RTTTL

## Admin Messages

* [x] Get device metadata

**Comment by kingoffoxes** [comment]
Looking forward to the power settings.
