### ISSUE TITLE
Feature Request: Channel Editor

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#197]
Some sort of limited channel editor
* [x] Update details (Name, uplink, downlink)
* [x] Delete Secondary Channels
* [x] Generate a new random psk

**Comment by ghostop14** [comment]
I'd add it would be nice to set a channel PSK like a wifi password from the mobile apps.  Say for small teams that don't want to connect to a computer but want to rotate keys.  Behind the scenes the "password" can be converted to hex if need be.  The user can be prompted for a minimum length, and it can be truncated once the necessary characters are reached if it's longer to meet the key length (but still keep it easy for a user to remember if it's longer).

**Comment by garthvh** [comment]
Random key generator 

func generateChannelKey() -> String {
	var keyData = Data(count: 32)
	let result = keyData.withUnsafeMutableBytes {
	  SecRandomCopyBytes(kSecRandomDefault, 32, $0.baseAddress!)
	}
	return keyData.base64EncodedString()
}

**Comment by garthvh** [comment]
> I'd add it would be nice to set a channel PSK like a wifi password from the mobile apps. Say for small teams that don't want to connect to a computer but want to rotate keys. Behind the scenes the "password" can be converted to hex if need be. The user can be prompted for a minimum length, and it can be truncated once the necessary characters are reached if it's longer to meet the key length (but still keep it easy for a user to remember if it's longer).

Current plan is to generate a random key like the python cli
