### ISSUE TITLE
Feature Request: Map Updates

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#210]
### Map Features

* [x] Enable switch for map type on node details map
* [x] Cluster pins (enabled for waypoints)
* [x] Enable switch for map type on mesh map
* [x] Create Waypoint Sheet when selecting location on the mesh map
* [x] Move mesh centering function to new map view
* [x] Filter mesh map down to location updates from the start of the current day
* [x] Center the map to show all the node position annotations on screen
* [x] Add option to center the map on all points (positions and waypoints)
* [x] Add annotation details with all the position flags for the local node or if we have position flags for the remote node
* [x] Update CoreData to store the latest position for a node as a boolean so that it is easier to query.
* [x] Show the latest position for a node in red, don't cluster it.
* [x] Add a position indicator to the pin if we have heading 
* [x] Keep app open and in the foreground when on the map view
* [x] Don't show the position arrows if follow with heading is enabled as they will not snap back to north and point in the correct direction.

#### Global Map Settings
* [x] Hook default map type up to app setting
* [x] User Tracking Mode

#### Mesh Map Settings
* [x] Map Centering - choose map centering option for the mesh map select from all annotations, all node positions or the client gps location
* [x] Potentially add a "refresh centering" option to choose weather to re-center or not

**Comment by djscoutmaster** [comment]
The Tasks we discussed added to this feature request

**1. Add - Auto Center Map on Phone GPS location :** 
- Auto center the map on the location of the phone GPS when the “mesh map” tab is selected
- As the phone GPS location moves, continue to keep the map centered on the most current phone GPS location
- User may pan, zoom to other areas of the map, the map may re-center on the phone GPS location after a period of 30 seconds of no touch or screen interaction activity
- _Optionally_ This setting can be enabled & disabled in the settings menu

**2. Add - Map heading setting**
- Add a UI element(button) on the “Mesh Map” to set map direction
- When the UI element is pressed set “up” on the map to be “north”
- When the UI element is pressed a second time set “up” on the map to the Compass heading from the phone
- Update the map heading direction frequently (at least every 200ms)

**Comment by garthvh** [comment]
Right now the map is always pointing north, if you scan around with your fingers and change the heading then the compass will appear and show where north is/

**Comment by djscoutmaster** [comment]
2 items I may have missed above 

- [ ] tapping the compass headed toggles between Up is north & compass headed is north
- [ ] Map centering on phone gps should update quickly around 100-200ms, or as quick as the phone provides a gps location update

**Comment by garthvh** [comment]
The arrow control on maps is called a MKUserTrackingButton apparently.  I did not have much luck with it, seems like it just toggles the [UserTrackingMode](https://developer.apple.com/documentation/mapkit/mkusertrackingmode)
