### ISSUE TITLE
Documentation on supported offline formats

### ISSUE THREAD

**Issue by geospatialmapmashup** [meshtastic/Meshtastic-Apple#241]
### OS

iOS

### Description

Is there any documentation on the supported offline formats
does the app support?

- MBTILES - Vector Tiles, Raster Tiles
- GPKG - Vector Features, Raster Tiles
- GeoJSON or KML or GPX

**Comment by garthvh** [comment]
MB Tiles are supported 

https://meshtastic.org/docs/software/apple/usage#offline-maps

**Comment by Techmaven-geospatial** [comment]
Should support vector tiles too and vector data
Seems limited only showing raster

**Comment by garthvh** [comment]
> Should support vector tiles too and vector data
> Seems limited only showing raster

MKOverlay only supports bitmaps or raster.
