### ISSUE TITLE
[Feature Request]: To open region Russia for AppStore

### ISSUE THREAD

**Issue by debitorka** [meshtastic/Meshtastic-Apple#257]
### OS

iOS

### Description

Region Russia unavailable now in AppStore
Please, open this region, if its possible

**Comment by ANS-spb** [comment]
I need it too

**Comment by garthvh** [comment]
Sorry, not possible

**Comment by Anonym-tsk** [comment]
> Sorry, not possible

What reason?

**Comment by sermelipharo** [comment]
Still required. Governmental censorship in Russia is rising up, and VPNs are already banned

**Comment by Leka1B** [comment]
It's needed more than ever with governments just up and cutting off the internet in some regions.

This would be the best available solution to governments controlling communication

**Comment by Flumeded** [comment]
> Sorry, not possible

If you need any contribution from my side, just let us know.
I am sure we can tackle the roadblocks you are facing

**Comment by Nenormalniy** [comment]
Colleagues, we turned off somewhere. We make a technology, not a political statement. Any of you can be in any emergency, in any country. We must try to spread such technology wherever possible.
What is the reason you made the application inaccessible in Russia? For what? To what?
