### ISSUE TITLE
[Feature Request]: Ability to add/move/delete shared markers on map

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-Apple#267]
### OS

iOS, iPadOS

### Description

It would be nice to be able to drop markers on the mobile maps.  Could be items of interest, waypoints, etc.  Would need add/update/delete capabilities on them as well.

**Comment by garthvh** [comment]
Its on the list
duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/210
