### ISSUE TITLE
[Bug]: Distance shown to node is incorrect

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/Meshtastic-Apple#279]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.8

### Description

IOS App shows incorrect distance to node 833 miles when node is in the same room. Map display is correct. See screenshots.

![IMG_3806](https://user-images.githubusercontent.com/121647809/210187983-666217af-72fa-4cb3-9361-16093ed2178d.jpg)
![IMG_3807](https://user-images.githubusercontent.com/121647809/210187984-8e9a296b-5138-41d7-9298-d20a3aa06c3a.jpg)

**Comment by garthvh** [comment]
I imagine this is how far you are located from the default location (Apple Park)

**Comment by GaryR-12** [comment]
OK thanks! I didn't think I needed the location permission to the app as my devices all have GPS. I assumed it would use the GPS location from the connected radio.
I will give the app permission.

**Comment by garthvh** [comment]
In 2.0.10 it won't show distance if the location is Apple Park, it still uses the phone GPS to calculate the distance from you.
