### ISSUE TITLE
[Feature Request]: Add Support for Different Display Layouts

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Apple#282]
### OS

iOS, iPadOS, macOS

### Description

Support for different screen layouts were recently added to the protobufs. When ready for client side, please add support for these within the app under Display Settings. Thanks! https://github.com/meshtastic/protobufs/pull/259/commits/9ba877271250f1a36a28432ee426a70affc841bd

**Comment by caveman99** [comment]
Just a short remark: the short-lived 2.0.10 default can be restored by displaymode "INVERTED" and heading_bold true. It's a really good mode for bigger TFT displays too, E-Papers better stick with the old/new defaults or use TWOCOLOR with or without the bold print.

**Comment by garthvh** [comment]
Will go out with 2.0.11
