### ISSUE TITLE
[Feature Request]: Ability To Delete Specific Node Entirely on Contacts Page

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Apple#289]
### OS

iOS, iPadOS, macOS

### Description

If possible add the ability to delete a contact (specific node) from the contacts page. This would be useful if a specific node no longer exists and you wish to clean up your contacts page without clearing entire app data. 

iOS and iPadOS can utilizes the swipe action. 

macOS make it a secondary click action.

**Comment by garthvh** [comment]
I had this feature at one point and with how the firmware is currently set up it causes a lot of confusion because often the node comes back in immediately from the device.

**Comment by garthvh** [comment]
This is on the node list now
