### ISSUE TITLE
[Feature Request]: Ability to Shutdown/Reboot Nodes within Network from Node Details

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Apple#292]
### OS

iOS, iPadOS, macOS

### Description

On Android you can send the Shutdown/Reboot commands to nodes you are not currently connected to via a client, but are connected to within the network. This is done from within the nodes list by long pressing a node and selecting the appropriate command. This option is not available within the Apple ecosystem, so I'm adding a feature request to implement the "Power Off"/"Reboot" buttons for other nodes within the network that are not client connected via their node details menu. 

Understandably this may not always work as it's being sent over the mesh, and admittedly I'm not sure what the limitations if any the android app may place on this, as I've only done limited testing, but the feature would still be a welcome addition to the Apple ecosystem. Thanks!

<img src="https://user-images.githubusercontent.com/6912600/212581262-a4a3a5b5-5022-46d9-ada6-ed4d232bb985.PNG" height=400>

**Comment by garthvh** [comment]
This will go out with 2.0.12
