### ISSUE TITLE
[Feature Request]: Use a confirmation button when saving

### ISSUE THREAD

**Issue by bmidgley** [meshtastic/Meshtastic-Apple#328]
### OS

macOS

### Description

This dialog window should have a confirmation button but instead it's just words and you guess where to click.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/63477/222975226-d1a94ac0-b09e-47c2-b27c-82325dcd7984.png">

**Comment by garthvh** [comment]
This control does not seem to be perfectly translated to catalyst yet, it has improved in the last few releases.

**Comment by garthvh** [comment]
Tracked here with the catalyst issues https://github.com/meshtastic/Meshtastic-Apple/issues/237
