### ISSUE TITLE
[Feature Request]: Add ability to share only secondary channels

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Apple#330]
### OS

iOS

### Description

I would like to be able to deselect primary channel when sharing QR codes

**Comment by garthvh** [comment]
Based on trying this when I built the code generator I don't think this works / is really confusing for most users.

**Comment by thebentern** [comment]
> Based on trying this when I built the code generator I don't think this works / is really confusing for most users. The webui offered this for a while and it did not work right.
This is probably due to channel indexing issues. I would propose that if you're only sharing a secondary channel, you're typically adding a "friend" to the mesh to setup their nodes, and in that case you'd want to share that as a single primary channel.

**Comment by garthvh** [comment]
Will release with 2.1.3
