### ISSUE TITLE
[Feature Request]: Charts for Channel and Airtime utilization in Device Metrics Logs

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Apple#343]
### OS

iOS

### Description

I would like to see line charts of Channel and Airtime utilization

**Comment by garthvh** [comment]
<img width="1492" alt="Screenshot 2023-04-01 at 9 38 42 AM" src="https://user-images.githubusercontent.com/1795163/229303522-b1c9d4ad-dc56-456c-8282-54ca1357b22b.png">

**Comment by garthvh** [comment]
I was not able to do lines for channel util and airtime, but I was able to get them on the same chart
