### ISSUE TITLE
[Feature Request]: Visually not clear where to click to save

### ISSUE THREAD

**Issue by TheRealCryss** [meshtastic/Meshtastic-Apple#362]
### OS

macOS

### Description

It isn't obvious where exactly to click in order to save the settings. There should be a visual hint for that when the mouse is not over the area and when it hovers over it as well. Clicking on Save (Speichern in DE) which highlights up when there was a change in the input fields doesn't save, which one would expect. Instead you have to click in a part of the pop-up message.

This report is for the current Meshtastic app from the Appstore on MacOS. I haven't tested it on other OSs.

![message](https://github.com/meshtastic/Meshtastic-Apple/assets/128715006/df6b1128-8b47-46f9-af27-de3951c4ba30)

**Comment by garthvh** [comment]
This is a Mac Catalyst issue, hopefully they enhance this control soon

**Comment by garthvh** [comment]
Duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/237
