### ISSUE TITLE
[Feature Request]: In-App Basic Resources/Help/Tutorials

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Apple#371]
### OS

iOS, iPadOS, macOS

### Description

I would like to suggest incorporating resources within the app to help new users.  Basically a section within the app that provides basic help guides, and/or tutorials. Things that can be easily be shown visually in the app, outside of just linking to the docs. This could include:

1. Getting Started Guide: A simple walkthrough for first-time users on how to set up and use the app and devices. Similar to what's currently shown on first-start in the android but updated and with more info.
2. FAQs: A list of frequently asked questions and their answers to help users troubleshoot common issues when using the apple apps. 
3. Tutorials: Step-by-step guides on how to use common features of the app. Essentially little slide shows for a given topic to help a user see visually.

What I'm envisioning are basic items specifically related to using the app, not configuring the devices (for this we can still refer to the docs). So an example "Adding a channel: Press the settings tab, make sure "Configure" says BLE: Node name, press the "channels" option under radio configuration, press "[+] add a channel" etc etc. But visually.

**Comment by garthvh** [comment]
Apple has added [TipKit](https://developer.apple.com/videos/play/wwdc2023/10229/) for iOS 17 which is probably what I would want to use.

**Comment by garthvh** [comment]
The bulk of the text in the app is also in a pretty easy to edit [single file)(https://github.com/meshtastic/Meshtastic-Apple/blob/main/en.lproj/Localizable.strings) and the places that are not in the file need to be done too.

**Comment by garthvh** [comment]
These are in place in the localizable string files now.  There are currently 3 tips.

https://github.com/meshtastic/Meshtastic-Apple/blob/9f9a1221552de54158585f53097bf06a63ba9d42/en.lproj/Localizable.strings#L279
