### ISSUE TITLE
Flickering signal graphic

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-Apple#381]
### Firmware Version

Latest

### What did you do?

On the Bluetooth screen, the signal graphic is flickering. May be a symptom of data coming on the edge of two display values. May need a hysteresis algorithm to stabilize. 

### Expected Behavior

Stable rf indicator. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mc-hamster** [comment]
https://github.com/meshtastic/Meshtastic-Apple/assets/12804989/2e4511b7-4d84-434f-b34b-fb352a72dcbb

**Comment by garthvh** [comment]
This is expected, those values update frequently, nrf connect (where the indicator code is from) does the same.
