### ISSUE TITLE
🚀 [Feature Request]: MapKit for SwiftUI Updates

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#398]
### OS

iOS, iPadOS, macOS

### Description

Update Maps to use MapKit for SwiftUI 

#### Features

* [x] Animated Last Position Pin
* [x] Smaller History Nodes 
* [x] Dashed route lines slightly lighter than the node color
* [x] Look around button
* [x] Settings Button and sheet / popover
* [x] Position Mac specific buttons
* [x] Show user tracking control for the connected node on the node map
* [x] Properly format heading in the position detail popover
* [x] Add waypoints annotations
* [x] Add waypoints editor form

##### Map Settings

* [x] Enable Route Lines
* [x] Enable Convex Hull
* [x] Enable Node History
* [x] Enable Traffic
* [x] Enable Points of Interest

#### Documentation

* [Apple Docs](https://developer.apple.com/documentation/mapkit/mapkit_for_swiftui)
* [Meet MapKit for SwiftUI](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiOyf697q2BAxUoIDQIHb4tDiUQwqsBegQIDRAB&url=https%3A%2F%2Fdeveloper.apple.com%2Fvideos%2Fplay%2Fwwdc2023%2F10043%2F&usg=AOvVaw2mKy29Cb8IgeoigwkFYgtP&opi=89978449)
* [Code from Meet MapKit for SwiftUI](https://github.com/turlodales/Content/blob/df0a8134be72203e6a8e7d49390a068e8890ef7b/content/notes/wwdc23/10043.md)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wschnell** [comment]
Hi,
looks like MapKit for SwiftUI is not in the package. Maybe needs to be bundled.
I installed the Meshtastic App from the Apple Store on my iMac running macOS 13.5.2 and the app crashes on start.
I do not have XCode or other developer components installed on this Mac.
thanks
Walter

**Comment by garthvh** [comment]
> Hi, looks like MapKit for SwiftUI is not in the package. Maybe needs to be bundled. I installed the Meshtastic App from the Apple Store on my iMac running macOS 13.5.2 and the app crashes on start. I do not have XCode or other developer components installed on this Mac. thanks Walter

Yeah it is only available in iOS 17 and macOS 14, not really sure why Intel Macs are trying to load it
