### ISSUE TITLE
 🚀 [Feature Request]: nodes on the Brazil map

### ISSUE THREAD

**Issue by Marlontebaldi** [meshtastic/Meshtastic-Apple#402]
### OS

iOS

### Description

Why don't the nodes appear on the Brazil map when I'm on the iOS app?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
What is the Brazil map?

**Comment by Marlontebaldi** [comment]
> What is the Brazil map?

When I create a fake location in any country other than Brazil, the node appears on the app's map, but when I put the location in Brazil, the app doesn't show it

**Comment by Marlontebaldi** [comment]
> What is the Brazil map?

nodes located in Brazil don't appear on the map. If I fake a location - anywhere other than Brazil, the app displays it correctly

**Comment by garthvh** [comment]
There is nothing preventing waypoints or nodes in Brazil, just added a waypoint and set a fixed position, I would review the Position setup on your node.

**Comment by Marlontebaldi** [comment]
![Imagem do WhatsApp de 2023-09-27 à(s) 14 12 29](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/c3041e61-bf9d-437a-b4e4-f304a6ccac48)
![Imagem do WhatsApp de 2023-09-27 à(s) 14 13 01](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/21e91c74-98ed-42c0-bbc7-7c898bc53351)
![Imagem do WhatsApp de 2023-09-27 à(s) 14 13 02](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/0be98ad8-a4f4-48cb-97fb-a25bb16e4490)
![Imagem do WhatsApp de 2023-09-27 à(s) 14 12 25](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/ad586145-e3cb-403e-95eb-55bf2f402b46)
![Imagem do WhatsApp de 2023-09-27 à(s) 14 12 26](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/7021c929-01e4-4d22-9dd5-d8746497f8b3)
![Imagem do WhatsApp de 2023-09-27 à(s) 14 12 27](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/54581daf-cecf-4bd5-823f-230807561611)

on android it works normally

> There is nothing preventing waypoints or nodes in Brazil, just added a waypoint and set a fixed position, I would review the Position setup on your node.

**Comment by Marlontebaldi** [comment]
> There is nothing preventing waypoints or nodes in Brazil, just added a waypoint and set a fixed position, I would review the Position setup on your node.

waypoints seem to work ok. the problem is with device positions. I have reproduced the problem by using a fixed position on my device (as show in the serial commands below)

roger-inspiron:~$ meshtastic --setlat 20 --setlon 20
Connected to radio
Fixing latitude at 20.0 degrees
Fixing longitude at 20.0 degrees
Setting device position
roger-inspiron:~$ meshtastic --setlat -20 --setlon 20
Connected to radio
Fixing latitude at -20.0 degrees
Fixing longitude at 20.0 degrees
Setting device position
roger-inspiron:~$ meshtastic --setlat -20 --setlon -20
Connected to radio
Fixing latitude at -20.0 degrees
Fixing longitude at -20.0 degrees
Setting device position
roger-inspiron:~$ meshtastic --setlat 20 --setlon -20
Connected to radio
Fixing latitude at 20.0 degrees
Fixing longitude at -20.0 degrees
Setting device position

![photo_2023-09-27_15-44-45](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/057a8938-4614-42f9-9b12-9c671ab05a25)

**Comment by garthvh** [comment]
Try with the latest version of the app, I am seeing quite a few southern positions on the public MQTT

**Comment by Marlontebaldi** [comment]
> Try with the latest version of the app, I am seeing quite a few southern positions on the public MQTT
![IMG_0954](https://github.com/meshtastic/Meshtastic-Apple/assets/140850787/1ccc80df-1e2d-4f2b-8773-04d38f6e2dff)

Now it's working, thank you, do you have any idea of ​​putting these iOS features in the Android app?

**Comment by garthvh** [comment]
These are all features of apple's maps, android is a whole different set of maps.
