### ISSUE TITLE
🐞 [Bug]: switching between channels does not work in UI

### ISSUE THREAD

**Issue by wschnell** [meshtastic/Meshtastic-Apple#408]
### Firmware Version

2.2.10

### What did you do?

I have the Primary channel as 0 AND a secondary channel as 1.
In the Apple Client, under messages, I want to switch between the 2 channels.

This happens in iOS (newest version) on my iPad AND in macOS 14.0 on my iMac.
Apple Client is 2.2.7 on each.

### Expected Behavior

the rightmost window shows the messages of the chosen channel.

### Current Behavior

the rightmost window does not switch between the (sets of) messages of the chosen channel.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wschnell** [comment]
same program logic as with switching between the DM threads, which works OK.

**Comment by wschnell** [comment]
workaround: close the Apple Meshtastic app and reopen, go to messages and choose the channel you want.

**Comment by garthvh** [comment]
Fixed in https://github.com/meshtastic/Meshtastic-Apple/pull/434
