### ISSUE TITLE
🚀 [Feature Request]: play sound when new message is received

### ISSUE THREAD

**Issue by wschnell** [meshtastic/Meshtastic-Apple#409]
### OS

iOS, iPadOS, macOS

### Description

The App could play a sound when a new message is received. On-Off in Settings. 
The luxury version would make the sound file configurable in Settings.

Side note:
There is the idea of connecting a buzzer or a speaker to the node device - this is completely unnecessary when it is connected to a Mac or iPad or iPhone.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
![IMG_1557](https://github.com/meshtastic/Meshtastic-Apple/assets/1795163/0942ca1d-5940-43e5-aa42-b8fa59349005)

This is managed by iOS

**Comment by wschnell** [comment]
Hi,
on my iPad, all notification options were set to ON upon installation, I get popup notifications, but no sound.
on my iMac, all notification were set to OFF upon installation, I set them to ON => I get popups, but no sound.
I will report if I find that I am doing something wrong ...

**Comment by garthvh** [comment]
On all three platforms permission on first launch pop ups are presented for BLE, location and notification permissions.
