### ISSUE TITLE
🚀 [Feature Request]: set focus on text input fields

### ISSUE THREAD

**Issue by wschnell** [meshtastic/Meshtastic-Apple#411]
### OS

macOS

### Description

For DMs and channel messages, it would be nice to have the focus on the text input field.
So one less click and it feels more natural.

In Swift, it is something like "focusedField".

In iOS and iPadOS I am not sure if this opens the keyboard, which I would not suggest.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
It already sets the focus, when you are in the 3 pane view and have selected the channel your selection is the middle column.  You can hit tab and it will go to the focused field
