### ISSUE TITLE
🐞 [Bug]: Tiny cosmetic bug (Linkbutton Not Working)

### ISSUE THREAD

**Issue by pmffromspace** [meshtastic/Meshtastic-Apple#413]
### Firmware Version

2.2.8

### What did you do?

I was looking around in the app settings, in the “About” section there is the button “Review this app”, I really like the app so I wanted to give 5/5 ;), unfortunately clicking it does not work… (reviewed it in AppStore anyway ;))

 

### Expected Behavior

Also it would be nice to have the app version written in the about section :)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wschnell** [comment]
App Version on iPhone and iPad would be helpful indeed.
On the Mac, there is the Mac Application About box that has it.

**Comment by garthvh** [comment]
The button works most of the time, apple does some throttling I don't control on that popup so it is imperfect.
