### ISSUE TITLE
Can't reset the nodes 🐞 [Bug]: 

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/Meshtastic-Apple#414]
### Firmware Version

2.1.23.04

### What did you do?

I Tried to delete all the nodes in the list from radios I just received from Lilygo (they all came with 20 nodes in them) I tried RESET NODEDB in Device Config, and tried FACTORY RESET in Device Config. (current IOS app).

### Expected Behavior

Expected the node list to be cleared.

### Current Behavior

Node list was not cleared or changed.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/427
