### ISSUE TITLE
🚀 [Feature Request]: Mark all messages as read.

### ISSUE THREAD

**Issue by hatesyourface** [meshtastic/Meshtastic-Apple#415]
### OS

iOS

### Description

This feature would be nice, but it came about because of a bug. 

iPhone 15 Pro, IOS 17, App v2.2.8

Peer sent an message that was heard over mqtt that wasnt encrypted on a mismatched channel number; that message is sent to the admin channel. On IOS I cannot view the admin channel (but verified that was the case on Android), therefore I cannot mark the message as read leaving a persistent notification badge I cannot clear. It would be nice to just mark all messages as read should the need arise. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
We will get the channel index fixed
