### ISSUE TITLE
🐞 [Bug]: node maps do not zoom and pan

### ISSUE THREAD

**Issue by wschnell** [meshtastic/Meshtastic-Apple#416]
### Firmware Version

2.2.10

### What did you do?

On the Mac:
in "Nodes" I choose a node that has a node map; then click on node map; a map with the position of the node appears.

### Expected Behavior

Node Maps should have zoom and pan capabilities like the Mesh Map.

### Current Behavior

the zoom factor in the node map cannot be changed.
the + and - buttons on the map do not work (although they are not grayed out).
Ctrl+ and Ctrl- do not work.
The Mac Application menu does not have Zoom entries.

in contrast:
the Mesh Map works as expected

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
These controls don't seem to be working in the latest version of Sonoma and have been removed in 2.2.9
