### ISSUE TITLE
🐞 [Bug]: Battery Curve Spline 

### ISSUE THREAD

**Issue by SSPW** [meshtastic/Meshtastic-Apple#421]
### Firmware Version

Latest ios

### What did you do?

Showed Device Metrics Log

### Expected Behavior

Expected accurate battery curve

### Current Behavior

Curve fitting used on battery curve displays loops. Would suggest using simple linear interpolation.

![IMG_6075](https://github.com/meshtastic/Meshtastic-Apple/assets/17904893/e215e967-823c-4ce5-bcad-8b6e210ad2d7)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This has already been addressed, not really interested in pinging back and forth with this setting., if you have big gaps between the data you will get imperfect splines like this either way anyways. This is how the SwiftUI charts manage this data.
