### ISSUE TITLE
🚀 [Feature Request]: FaceID/Password lock on the app for safety

### ISSUE THREAD

**Issue by RCGV1** [meshtastic/Meshtastic-Apple#423]
### OS

iOS, iPadOS

### Description

I think it would be useful for users who want added security for a lock option to be added to the app so the wrong people cannot message or read messages on their behalf.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
I don't really want to manage an app only password, without some firmware support I am not sure what this would really do.

**Comment by RCGV1** [comment]
There is a native way to do this. https://www.hackingwithswift.com/books/ios-swiftui/locking-our-ui-behind-face-id

**Comment by garthvh** [comment]
Yeah I have looked at it before https://developer.apple.com/documentation/localauthentication/logging_a_user_into_your_app_with_face_id_or_touch_id/ it is meant to be used with some sort of backing login system, which the device does not have yet and does not exist in the app either.

**Comment by garthvh** [comment]
This is only done by financial institutions, there is no Face ID lock for messages because it is too much friction.
