### ISSUE TITLE
🐞 [Bug]: Seems like the signal strength reported on the device and the app is not aligned

### ISSUE THREAD

**Issue by runestone74** [meshtastic/Meshtastic-Apple#430]
### Firmware Version

2.2.13

### What did you do?

Signal strength in the app and on the T-Echo display are not matching up.
![IMG_5368](https://github.com/meshtastic/Meshtastic-Apple/assets/25870931/b269ec19-0e5a-4e0a-8ec4-afc45d9f5d7b)
![IMG_5369-EDIT](https://github.com/meshtastic/Meshtastic-Apple/assets/25870931/d79ec7ba-2af6-428e-81be-cea52f0b74ac)

### Expected Behavior

The signal meter should reflect the lower signal strength

### Current Behavior

It always looks like high signal strength

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Not the same calculation
