### ISSUE TITLE
🚀 [Feature Request]: improve intuitivity for GPS 

### ISSUE THREAD

**Issue by TobiasPSP** [meshtastic/Meshtastic-Apple#431]
### OS

iOS

### Description

I started playing with Meshtastic recently, using Heltec V3 and iPhone app. Everything worked like a charm, left me deeply impressed.

The only thing that took me days to figure out was sending GPS position data gathered by my iPhone via the heltec V3. 

The solution turned out to be so trivial: I simply did not enable "publishing position in mesh" in the app settings (I have a localized app and translated the menu item, the original menu item may be named slightly different). 

This setting was disabled by default (which is a good thing privacy-wise). 

What confused me is that Meshtastic documentation states that the setting "GPS enable" is enabled by default (https://meshtastic.org/docs/configuration/radio/position#gps-enabled).

So when GPS did not work, I was all focused on the settings listed in the tab "Position". It did not occur to me at all that the main ON/OFF switch for sending position data was burried elsewhere in the app settings.

Cut long story short: IMHO the setting "Publish position to mesh" is part of Position config and as such should not be separated from all the other "Position" settings and should be located on the page "Position Configuration". 

In my naive intuitive world, the page Configuration - Position in the future would feature a big ON/OFF switch on top, then followed by the existing settings in "Position Packet". That would make total sense to me.

Now that I got it to work I could care less, yet everything else in Mashtastic worked so intuitively and with such ease whereas GPS setup took me days of googling and scratching my head, So maybe my newbee perspective helps you making the user experience yet another tiny tick slicker.

That said, you are doing such an amazing job, and I am deeply impressed by your implementation. Awesome work, many thanks.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by TobiasPSP** [comment]
Something related: from what you say, I assume that the „Publish to Mesh“ setting is controlling solely the use of the host GPS. 

It‘s confusing, too, because I assumed that the setting would also apply to hardware with dedicated GPS modules and control whether they publish their position. Apparently from what you say that is not tge case.

In summary, as a constructive feedback with best intentions, I‘d suggest reviewing the paradigm how GPS is controlled via app.

From a user perspective, what I want to control is whether I publish my position or not, and what the intervals and details are. I wouldn‘t care much about whether the GPS receiver is located on the device or on the host.

**Comment by garthvh** [comment]
App settings are for things that do not need to send a message to the device to save.

This setting is off by default, so you enabled it at some point,

**Comment by garthvh** [comment]
Feel free to update the translation if it is not correct.

**Comment by TobiasPSP** [comment]
> Feel free to update the translation if it is not correct.

Translation is perfect, I just didn’t know if I translated it correctly back to English. I did not want to post the localized name that I see in my app 😀 so all is good!
