### ISSUE TITLE
🐞 [Bug]: Location issue

### ISSUE THREAD

**Issue by I3rixon** [meshtastic/Meshtastic-Apple#433]
### Firmware Version

2.2.14 last version

### What did you do?

Location issue.
Tried used fixed posotion. Set on Adnroid, then connect on iPhone - and app set it to zero/wiped.
Tried also from Python console version of Meshtastic - it worked, BUT calculation between nodes not correct. in reality it cople of km but in app it wrote ~6800 km like not found correct location
As I remember in prev version I don't have that issue.
I have tried reinstall and different versions of firmware - the same result.
Location from GPS in iPhone not set also, only fixed. Not shared location

### Expected Behavior

Correct location from iPhone GPS should be work

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
When you enable the fixed position checkbox it sends your current location to the device as your position.

**Comment by I3rixon** [comment]
no. it not worked. it set to zero lat/long/alt

**Comment by I3rixon** [comment]
permision to GPS in granted for that app

**Comment by garthvh** [comment]
Those positions are being sent into the phone, I don't see where you have set fixed position.

Are you on iOS 17?

**Comment by I3rixon** [comment]
![IMG_0192](https://github.com/meshtastic/Meshtastic-Apple/assets/1359864/b76e3f57-cf64-47b7-a75c-881a4028d52d)
iOS 17.

**Comment by I3rixon** [comment]
with fixed position as you can see it empty
![Screenshot_69](https://github.com/meshtastic/Meshtastic-Apple/assets/1359864/89ee40ae-e8d7-444c-a485-c82f18791d0a)

**Comment by garthvh** [comment]
I think you need to upgrade your firmware, that is probably the right distance to null island

**Comment by I3rixon** [comment]
firmware is 2.2.16 is last one (tested other versions too). I have posted version of App what I used is 2.2.14 also last
