### ISSUE TITLE
🐞 [Bug]: Distances in node list are to lat,lon 0,0 instead of actual location 

### ISSUE THREAD

**Issue by gitToad** [meshtastic/Meshtastic-Apple#438]
### Firmware Version

2.2.15

### What did you do?

I have a bunch (15) Meshtastic devices on our mesh, some T-Echos, some T-Beams, some Garth devices. Some have GPS, a few do not.
using various (relatively recent 2.2.12 and up) firmware versions and app version 2.2.15
Connecting to any node, looking at node list in the app and specifically the distance in miles to the node shown.

### Expected Behavior

Expect to see the distance from myself (either BT connected device or phone/laptop, not sure which one is intended to be used of the two) to each node in the node list that has transmitted at least one position packet.

### Current Behavior

![Untitled](https://github.com/meshtastic/Meshtastic-Apple/assets/503035/57d24ee4-94a3-41a6-a12e-55aea290e2af)

In the device list (on Mac & iOS), devices for me appear 7956 miles away (I am in SF Bay Area and this is the distance to lat, lon = 0,0) This is regardless of whether I am connected to a node that HAS or HAS NOT got GPS onboard. It also does not matter whether the app is sharing location or not. 

Both the laptop and phone themselves know their location correctly (ie I can go into Google Maps and the blue dot is in the correct place) so I suspect this is a bug in the app, where the "self" location is somehow 0,0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ERF1994** [comment]
![IMG_8925](https://github.com/meshtastic/Meshtastic-Apple/assets/40825719/7ca5d59f-1368-4343-b22c-6e5fa55fe546)

same problem, my node T-beam v1.1, ios17.2.1 updated Meshtastic app. When I switch to legacy map the distance on map displayed right, but node list still wrong.

**Comment by gitToad** [comment]
Possibly related (ie if app erroneously thinks it is at 0,0 then those distances make sense)
Seeing lat lon 0,0 reported on meshtastic app 
• on ios 17.2.1, app version 2.2.16 as well as 
• Mac OS 14.2.1 app version 2.2.15
![unnamed4](https://github.com/meshtastic/Meshtastic-Apple/assets/503035/703f8882-a8de-4de2-9ec7-c84051ffc259)

**Comment by guillochon** [comment]
GPS locations appear to be broken in several versions of iOS for me (Tried iOS 17.1.2, 17.2.1, and iPad OS 17.1.1) on the latest version of the Meshtastic app. I see my GPS being 0, 0 regardless of whether I am paired to a device or not.![image](https://github.com/meshtastic/Meshtastic-Apple/assets/4998058/48c020dd-271b-4e4e-a635-852dc7ba2e86)

**Comment by ayypablopablo** [comment]
iPad mini 6th gen on OS 16.5.1  Location settings show the purple location checkmark (active) for Meshtastic.  Meshtastic sees 7 satellites and coordinate positions

iPhone 15 Pro on OS 17.2.1 
No active location (purple location checkmark) at any point with Meshtastic open. Meshtastic displays 000000,00000 coordinates and specifies estimated 1 satellite.

Findings for both devices above occurred at the same time. Meshtastic version 2.2.16

**Comment by mesh100A** [comment]
I'm having the same issues. With IOS 16.7.4 and the latest Meshtastic APP. I see in app settings 7 sats and the correct co-ordiantes for my location but my Heltec V3 does not show KM and just a ? in the circle GPS. So in this setup the App is taking the Coorodiantes from the mobile to app but no displaying them on the unit. When I move to IOS 17.2.1 and latest app nothing works. No co-ordiantes in mash appo and still no GPS data on V3. Meshtastic displays 000000,00000 coordinates

**Comment by mesh100A** [comment]
![ios 16 7 1](https://github.com/meshtastic/Meshtastic-Apple/assets/154735481/176143da-f2ca-41a2-a484-2b84a577ea06)

**Comment by mesh100A** [comment]
![garth1](https://github.com/meshtastic/Meshtastic-Apple/assets/154735481/d397dae3-04a9-47b4-81ce-4c36dfcab78e)

**Comment by mesh100A** [comment]
![broken](https://github.com/meshtastic/Meshtastic-Apple/assets/154735481/ef85478f-4b64-4bd9-9c98-89a8fad13b2c)
This is the display on either ios 16.7.4 or 17.2 and 17.2.1 If you roll back the app to 4 revisons it works I have been told

**Comment by I3rixon** [comment]
Last version of App 2.2.16 
![IMG_0200](https://github.com/meshtastic/Meshtastic-Apple/assets/1359864/6dedaa09-bee6-4d58-8440-0eab1028f813)

**Comment by postcatz** [comment]
just built the all myself and location and location reporting work fine!

**Comment by postcatz** [comment]
the isssue is fixed in 2.2.17 and will most likely be released very soon

**Comment by Kiloa1** [comment]
I have the same issue as above. The app was working perfectly and sharing data to the node.
Yesterday I removed and reinstalled the app from fresh, the coordinates were no longer being sent to the Heltec board. I could see the coordinates in the app. 
To try and resolve the issue i decided to update IOS to the latest revision and suddenly the issue was worse.
No the coordinates!  the same issue as others are reporting. Basically they are not being picked up or sent to the board.

**Comment by postcatz** [comment]
@Kiloa1 it's already fixed and will be released soon

**Comment by mesh100A** [comment]
> @Kiloa1 it's already fixed and will be released soon

thank you so much, cant wait
