### ISSUE TITLE
🐞 [Bug]: Need to reconnect to node twice to get firmware version correct 

### ISSUE THREAD

**Issue by gitToad** [meshtastic/Meshtastic-Apple#446]
### Firmware Version

Mac app Version 2.2.17 (754)

### What did you do?

Not sure how to title this. Or whether it is a bug or feature enhancement request. 

Repeatably, after disconnecting from a node and then connecting to another node via Bluetooth on my Mac (M1 Laptop, 14.2.1), the node connects, "communicating with device" animation, and then 2 things happen:

1. firmware version always shows as "Unknown"
2. switching to "Settings" screen, I get some orange warnings and cannot yet edit device parameters (I believe it is actually showing stale data from the last connected device)

BUT (this is the workaround also):
When DISCONNECTING AND RECONNECTING to the same device, now the firmware version shows correctly and after switching back to "Settings" once more, the warning message has disappeared and the device parameters are editable.

This behavior appears independent of what kind of device connects (ie I have seen it on ESP32 Heltec v3's as well as RAK4630's)

### Expected Behavior

It feels like the first time after connecting, something is left uninitialized or incomplete and after reconnecting to the same device, things work as expected.

### Current Behavior

1. switching to Bluetooth and then back to Settings makes the device parameters editable
2. switching to Bluetooth and disconnect/reconnect to same device makes the firmware version show correctly

Feel free to change from a bug to a feature request (or close it) if this is just a minor UI nuisance. Filing it just in case it points to some potential unintended behavior.

Thank you !

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by gitToad** [comment]
Here is a picture of the sequence of events if that makes it any clearer:
![unnamed6](https://github.com/meshtastic/Meshtastic-Apple/assets/503035/c94165c7-fd04-4b2c-b1ef-e8b2529980d0)

**Comment by garthvh** [comment]
There is a fix for this in TestFlight, will be in the next release
