### ISSUE TITLE
🐞 [Bug]: Location from phone being pushed to node too frequently

### ISSUE THREAD

**Issue by guillochon** [meshtastic/Meshtastic-Apple#447]
### Firmware Version

2.2.16.1c6acfd

### What did you do?

I took these three photos in quick succession (over 5 seconds) after a fresh restart of a node. As you can see from the app settings the position shouldn’t be updating this frequently. I had turned off my other node entirely during this test, it’s just one node and the phone. The node became unresponsive to button presses within about 20 seconds of power on.

![IMG_6300](https://github.com/meshtastic/Meshtastic-Apple/assets/4998058/4386cfd9-6219-447e-a238-093ab1dc04ee)
![IMG_6294](https://github.com/meshtastic/Meshtastic-Apple/assets/4998058/3cb99d7a-b15a-4403-9e44-d5d281f11c57)
![IMG_6295](https://github.com/meshtastic/Meshtastic-Apple/assets/4998058/9c4c9c0a-0188-4b7a-92e4-24e9e009b99e)
![IMG_6296](https://github.com/meshtastic/Meshtastic-Apple/assets/4998058/23cd0ce6-903d-4374-98cb-2ab45594675d)

### Expected Behavior

Location should only be pushed once every 30 seconds (or whatever is set in the App Settings)

### Current Behavior

Location appears to be pushed every few seconds, as indicated by the wildly fluctuating arrow.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by guillochon** [comment]
This is still affecting me. Can I provide some debug info? Any sort of acknowledgement from the team that the issue exists?

**Comment by guillochon** [comment]
I was able to resolve this by clearing the app settings and then reinstalling the app entirely. Hasn't recurred since then, but I'll keep this open for now to see if others encounter the same thing.

**Comment by guillochon** [comment]
Was working fine for about a week, but have run into this issue again. I have since upgraded the firmware on the node to 2.2.17. Turning off "location sharing" in the App Settings seems to make the node responsive, but as soon as I turn it on, it's unresponsive. Dunno if that's because the location is indeed being shared too frequently or what.

**Comment by garthvh** [comment]
There is a fix in test flight preventing 0 as the timer interval.

**Comment by guillochon** [comment]
Thanks @garthvh!
