### ISSUE TITLE
🐞 [Bug]: Whacky timestamps in Device Metrics Log

### ISSUE THREAD

**Issue by GaryR-12** [meshtastic/Meshtastic-Apple#451]
### Firmware Version

2.1.23.04bbdc6

### What did you do?

![IMG_6205](https://github.com/meshtastic/Meshtastic-Apple/assets/121647809/d8a92759-2f6b-4ff1-96bc-7f47eb59dfe5)

### Expected Behavior

Appropriate dates.

### Current Behavior

The first entry in the Device Metrics Log is almost always UNKNOWN TIME and sometimes the dates are wacky (1969 and 2009) as shown in the attached screenshot.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The app just displays data it gets from the device
