### ISSUE TITLE
🚀 [Feature Request]: also show node name in mesh log ?

### ISSUE THREAD

**Issue by gitToad** [meshtastic/Meshtastic-Apple#452]
### OS

iOS, iPadOS, macOS

### Description

Would it be possible to also show the node NAME (long/short) for received messages in the Mesh Log ? That would make it easier to figure out for a human where messages came from than just node number. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Would be a performance hit that is probably not worth it.
