### ISSUE TITLE
🐞 [Bug]: Can't save settings

### ISSUE THREAD

**Issue by jiveman** [meshtastic/Meshtastic-Apple#457]
### Firmware Version

2.2.16

### What did you do?

Launch meshtastic App for MacOS  > Settings > change a setting and hit Save. 

### Expected Behavior

Saves setting

### Current Behavior

popup confirmation "Are you sure?" and no way to save the setting. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
<img width="1321" alt="Sure" src="https://github.com/meshtastic/Meshtastic-Apple/assets/1795163/6a58a732-18cc-4768-b505-f43dae19a8a3">

What os version are you running, confirmation dialogs are fixed in Sonoma.
