### ISSUE TITLE
🐞 [Bug]: Mac version memory leaks

### ISSUE THREAD

**Issue by gitToad** [meshtastic/Meshtastic-Apple#459]
### Firmware Version

2.2.17 (754)

### What did you do?

Keep the mac version running for hours/days. It will consume more and more memory and become quite slow. Eventually it causes a system alert: out of memory. At that point Meshtastic was using 9 GB 
I have about 15 devices on the mesh, and there was no real text message traffic (ie mostly nodeinfo, position, telemetry updates) 
I don't know how but if I can help narrow it down somehow I am happy to help, let me know what tools/procedures to use.

### Expected Behavior

The app should work "always on" (I think) During an event, we would keep it running at our command post continuously.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Yeah catalyst is always improving, but it struggles after long periods currently
