### ISSUE TITLE
🐞 [Bug]: RTTTL format cannot contain spaces

### ISSUE THREAD

**Issue by RWilkus** [meshtastic/Meshtastic-Apple#463]
### Firmware Version

2.2.17

### What did you do?

RTTTL formatting does not specify if it can contain spaces or not but if they are included the output does not function as expected. Removing spaces before sending to protobuf will produce the expected output or include a tool tip to inform the user of correct formatting. 

### Expected Behavior

RTTTL format cannot contain spaces before being sent to firmware. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Input formatting could include spaces but should be removed before being sent to firmware or add UI information on proper formatting.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/465 Updated in test flight, submitted to the App Store
