### ISSUE TITLE
Cannot set correct pin mapping for GPS module - Heltec Lora V3🐞 [Bug]: 

### ISSUE THREAD

**Issue by mattriney** [meshtastic/Meshtastic-Apple#467]
### Firmware Version

2.2.17

### What did you do?

When configuring  GPS in Settings>Position>Device GPS, the list of pins does not include "Pin 48."

### Expected Behavior

The listing of GPIO pins is incomplete for this board, "Pin 48" needs to be included.

### Current Behavior

The application provides a list which does not include "Pin 48."

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/465 Updated in test flight, submitted to the App Store
