### ISSUE TITLE
🐞 [Bug]: Unable to automatically reconnect to T-Beam Supreme devices; "Forget and Re-Pair" required to reconnect.

### ISSUE THREAD

**Issue by the-toph** [meshtastic/Meshtastic-Apple#469]
### Firmware Version

2.2.19

### What did you do?

I am unable to reconnect an iOS device (14 Pro Max) to a T-Beam Supreme device via Bluetooth after the initial connection. I have to forget and re-pair every time, after the first connection disconnects.

I have no issues with the iOS app connecting to my T-Echo's.
I have no issues with the Android app connecting to my T-Echo's OR my T-Beam Supremes.
I have also tried a different iOS device (14 Pro), and encountered the same issues.
Tested Meshtastic Firmware 2.2.14, 2.2.17, 2.2.19 - Issue persists.

Unfortunately I don't know which app version this started with. I don't believe it started in 2.2.18. I swapped to Android for about 2 months and it happened in between.

### Expected Behavior

Assuming you've never paired to this T-Beam Supreme device....
1. Open the Meshtastic App, and select a device you haven't connected to, perform the Pairing process, device pairs and connects.
2. Disconnect the Bluetooth connection, either by selecting "Disconnect" in the app, swiping the Meshtastic app closed, or by going out of range of the device.
3. Reconnect to the device, either by tapping the device name in the Meshtastic Bluetooth screen, or opening the app and allowing it to reconnect.
4. Device reconnects successfully.

### Current Behavior

Assuming you've never paired to this T-Beam Supreme device....
1. Open the Meshtastic App, and select a device you haven't connected to, perform the Pairing process, device pairs and connects.
2. Disconnect the Bluetooth connection, either by selecting "Disconnect" in the app, swiping the Meshtastic app closed, or by going out of range of the device.
3. Reconnect to the device, either by tapping the device name in the Meshtastic Bluetooth screen, or opening the app and allowing it to reconnect.
4. The reconnection fails.
5. In order to reconnect, you need to close out of the Meshtastic app, then go to iOS Settings > Bluetooth, forget the device, then re-connect and re-pair in the Meshtastic app (start at step 1).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Can't replicate this issue
