### ISSUE TITLE
USB upgrade drag and drop to com port

### ISSUE THREAD

**Issue by bfro850** [meshtastic/Meshtastic-Apple#471]
### OS

iOS

### Description

I was wondering if somebody could build something for Meshtastic heltec.cn Lora 32 ESP version three Drag and Drop , various routes and other things, update, etc.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Apple does not allow generic serial access.  You can use drag and drop firmware updates if your phone has USBC, or if you use the USB camera adaptor.
