### ISSUE TITLE
🚀 [Feature Request]: Add canned message feature to the iOS app

### ISSUE THREAD

**Issue by drewzh** [meshtastic/Meshtastic-Apple#473]
### OS

iOS

### Description

Please add the ability to add canned responses. It's often I have to send a common message and currently each time I have to type out the message or copy and paste from a previous message, which isn't a create UI. Often I'm on the go where having easy access to a canned response would be very handy. I envision a feature whereby you can click the canned message icon and then select from a list of pre-defined messages. This list should just be a simple list of strings that can be easily added to via a "Add new..." option at the bottom of the list.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The right way to do this on iOS is with text replacement or a custom keyboard, both options are available already.  No plans to add quick messages like android.
