### ISSUE TITLE
🐞 [Bug]: Incorrect visualization for the configuration of the detection sensor.

### ISSUE THREAD

**Issue by OE4DEA** [meshtastic/Meshtastic-Apple#476]
### Firmware Version

2.2.17

### What did you do?

Incorrect visualization for the configuration of the detection sensor.

![Screenshot](https://github.com/meshtastic/Meshtastic-Apple/assets/158557648/ea1415c6-ce5a-4dcd-bcc3-25aff907ad79)

### Expected Behavior

Rename to "Detection Sensor".

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by OE4DEA** [comment]
> What language are you using?

I use German.

**Comment by garthvh** [comment]
closed by https://github.com/meshtastic/Meshtastic-Apple/pull/472 

They are just the English versions so they will need translation.
