### ISSUE TITLE
🐞 [Bug]: Display error on Device Metrics Log and Environment Metrics Log

### ISSUE THREAD

**Issue by moresecode** [meshtastic/Meshtastic-Apple#489]
### Firmware Version

2.2.21

### What did you do?

Hardware use: RAK4631 + RAK1906 (BOSCH BME680)

Nodes > tap on my node > Device Metrics Log
Nodes >  tap on my node > Environment Metrics Log

### Expected Behavior

Display readable information.

### Current Behavior

Those green and yellow dots are all over the places.
![B6A50EA0-CED5-4FBE-ACBB-EB78A586227B_1_201_a](https://github.com/meshtastic/Meshtastic-Apple/assets/63538521/23199261-9818-4c27-b697-f27415aa02bd)

Temp reading has too much decimal places.
![8B17DC90-602A-4EC7-B16A-B45D806F8609_1_201_a](https://github.com/meshtastic/Meshtastic-Apple/assets/63538521/3581c20c-1cdd-4077-b68a-981eeb52b9dd)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Channel utilization and airtime bounce around a lot more.

**Comment by garthvh** [comment]
There is another option for "width" for the measurement values, the next App Store release will use narrow for temperature.  The scatter plot for channel utilization is the the right visualization for something than can bounce around so much, you can see in that data there are potentially 10% or more jumps every minute.
