### ISSUE TITLE
🐞 [Bug]:  unresponsive after viewing maps

### ISSUE THREAD

**Issue by aptonline** [meshtastic/Meshtastic-Apple#499]
### Firmware Version

2.2.21.7f7c5cb Beta

### What did you do?

After viewing the map, which has close to 100 nodes, the entire app becomes unresponsive.  When I do manage to be able to send a message the keyboard lags slower than before the previous fix.

### Expected Behavior

Interface should be responsive to taps and interactions.

### Current Behavior

As above, interface not responsive after viewing maps with a lot of pins.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Latest iOS app and latest beta firmware

**Comment by garthvh** [comment]
Not seen any lag with 150+ nodes now
