### ISSUE TITLE
🚀 [Feature Request]: client version should be able to connect to meshtastic.local

### ISSUE THREAD

**Issue by AssetBurned** [meshtastic/Meshtastic-Apple#506]
### OS

iOS, iPadOS, macOS

### Description

it would be great if the app could also connect to a client that is not connected via Bluetooth, but within the same network (e.g. meshtastic.local)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Adding TCP connections would require refactoring the whole app, not on the roadmap.
