### ISSUE TITLE
🐞 [Bug]: Map broken when viewing trace route between 2+ nodes

### ISSUE THREAD

**Issue by drewzh** [meshtastic/Meshtastic-Apple#510]
### Firmware Version

2.2.22

### What did you do?

Perform traceroute to client node that goes via an intermediate node. All nodes in question have location data set 

### Expected Behavior

Should show line between client, router and client on the map

### Current Behavior

Map fails to load

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

![IMG_CC14464B881A-1](https://github.com/meshtastic/Meshtastic-Apple/assets/344724/14b7b9f8-cab3-4329-a73e-56daaef21014)

**Comment by garthvh** [comment]
The map only shows if we have a recent position from each node

**Comment by drewzh** [comment]
> The map only shows if we have a recent position from each node

As mentioned, all nodes have location data set. The client has GPS fix as of only minutes earlier, the router location is static and recently reported/on the map and the endpoint client node has a static location set/reported earier and viewable on the map.

**Comment by drewzh** [comment]
Just a small note also, though more anecdotal - I've never seen a multi-hop traceroute show correctly, only single hop. This is in my 2 months of testing on iOS using various nodes in the field.

**Comment by garthvh** [comment]
I tested this a few times and got maps for multiple hop trace routes.  I may need to make the timeframe longer than an hour.
