### ISSUE TITLE
🚀 [Feature Request]: Copying the UserID by taping on it.

### ISSUE THREAD

**Issue by AssetBurned** [meshtastic/Meshtastic-Apple#514]
### OS

iOS, iPadOS, macOS

### Description

When being in the view that shows the nodes details, it would be great if i could tap on the UserID and copy it that way.

Currently there is no way of getting that ID in an easy way and doing something with it.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Doing what with it?

**Comment by AssetBurned** [comment]
Using it e.g. in a chat group chat.
That information stays the same per node as far as I can see.
