### ISSUE TITLE
🚀 [Feature Request]: linking Nodes Map to the Direct Channel and Details of the node

### ISSUE THREAD

**Issue by AssetBurned** [meshtastic/Meshtastic-Apple#520]
### OS

iOS, iPadOS, macOS

### Description

Hi,
When you are looking at the Nodes Map view and tap on a single node. You get some of the details of the node.
But getting from there to send a direct message to the node or get the page that allowed you to see the various logs of that node, requires a lot of taping.

Therefore the suggestion to add two buttons. One to get the the view to see the logs etc and one to open the direct chat.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tekstrand** [comment]
I was coming here to write this feature request. I propose that there is interlinking between all pages. 

1. From the DM you should be able to tap the name at the top similar to how the iOS Messages app works - it should allow you to open the contact.
2. From the Node detail page, you should have a "Write new message" button, same as viewing a contact in iOS
3. From the map you should be able to tap the icon and get to the Node(contact)
