### ISSUE TITLE
🚀 [Feature Request]: Option to show the Admin channel

### ISSUE THREAD

**Issue by AssetBurned** [meshtastic/Meshtastic-Apple#521]
### OS

iOS, iPadOS, macOS

### Description

The admin channel is not shown in the channel list. Which causes a bit of confusion when looking at the channel list and have a number missing in between.

It would also allow to work around situations where you may get a message in that channel (see https://github.com/meshtastic/Meshtastic-Apple/issues/483 )

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The admin channel is not for messaging.
