### ISSUE TITLE
🚀 [Feature Request]: More Time Interval Selections for Position Broadcast Interval

### ISSUE THREAD

**Issue by jonathantdo** [meshtastic/Meshtastic-Apple#524]
### OS

iOS

### Description

When Smart Position broadcast is disabled, it defaults to a 15-minute interval for GPS connection updates. It would be beneficial to have options for shorter intervals like 30 seconds and 1 minute to provide more frequent updates, especially for users who turn off Smart Position.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
You should be using smart position if you want more frequent updates, broadcasting every 30 seconds is really bad for the mesh.

**Comment by garthvh** [comment]
I did add 5 and ten minute options back

**Comment by jonathantdo** [comment]
Thank you @garthvh!
