### ISSUE TITLE
🚀 [Feature Request]: Update all Settings Views to be Translatable

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#525]
### OS

iOS, iPadOS, macOS

### Description

There are lots of strings that are in the configuration views instead of being in the Localizable files where they belong.

## Config

* [ ] LoRa
* [ ] Channels
* [ ] Share QR Code
* [ ] User
* [ ] Bluetooth
* [ ] Device
* [ ] Display
* [ ] Network
* [ ] Position
* [x] Power

## Module Config

* [ ] Ambient Lighting 
* [ ] Canned Messages
* [ ] Detection Sensor
* [ ] External Notification
* [ ] MQTT
* [ ] Range Test
* [x] Pax Counter
* [x] Ringtone
* [ ] Serial
* [ ] Store & Forward
* [ ] Telemetry

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by AssetBurned** [comment]
https://github.com/meshtastic/Meshtastic-Apple/issues/535 and https://github.com/meshtastic/Meshtastic-Apple/issues/383 for whoever followed those.

**Comment by garthvh** [comment]
Upgraded to new translation system
