### ISSUE TITLE
iPhone App Crashes 🐞 [Bug]: 

### ISSUE THREAD

**Issue by PCServices2** [meshtastic/Meshtastic-Apple#528]
### Firmware Version

2.2.22

### What did you do?

Updated the iPhone App today. Nothing else has changed.
When I try to connect to two of my three nodes, the App crashes. I reopen the App and it crashes again as soon as it establishes a connection to the node. The only way to keep the App open is to quickly disconnect the node before it crashes.
I can connect to one node (Heltec v3) but not the other two (A Heltec v3 and T-Echo). All nodes are on Firmware 2.2.22

### Expected Behavior

The App should connect to the 'new' node and not crash.

### Current Behavior

The App crashes as soon as it connects to two of my three nodes

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aptonline** [comment]
I’m finding the iOS app buggy and unresponsive.

Out of interest how are you connecting to and switching between multiple nodes in the iOS app? I’ve just purchased another Heltec but can’t see a way to add it as already have another node setup.

thanks.

**Comment by PCServices2** [comment]
> I’m finding the iOS app buggy and unresponsive.
> 
> Out of interest how are you connecting to and switching between multiple nodes in the iOS app? I’ve just purchased another Heltec but can’t see a way to add it as already have another node setup.
> 
> thanks.

You swipe to the left on the node that you have connected, then click “disconnect“. 

You can then connect to the other node.

**Comment by aptonline** [comment]
Wow didn’t know that, thanks. 

I’ve raised a few tickets on here and no reply yet which is a shame. Wanting to make the app better for all but we need engagement from the devs.

**Comment by garthvh** [comment]
Nothing actionable here, include some logs or details on what crashed, enable crash reporting on your phone.
