### ISSUE TITLE
🚀 [Feature Request]: Nodes tab > Nodes list: add ping feature and improve node connectivity status

### ISSUE THREAD

**Issue by Myrlhyn** [meshtastic/Meshtastic-Apple#532]
### OS

iOS, iPadOS, macOS

### Description

In order to help the end user to manage the surrounding nodes, it would be nice to have the following:
1- app issues a --sendping to all nodes when the screen is dragged down (see image below)
2- turn all coloured information (circle under node's short name, signal strength ...) to grey when the node is no more available. Doing so, one can identify immediately the status of the mesh. (see image below)

![nodeRefresh](https://github.com/meshtastic/Meshtastic-Apple/assets/161041172/cc5520d5-c92d-4f16-97d9-e5be6fa50ac6)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Seems like a lot of gray, I like the existing online indicators more than a bunch of gray.  The signal meter has been removed from MQTT nodes in the release currently in app review.

**Comment by Myrlhyn** [comment]
Thank you for your response. it is really up to you to decide what level of emphasis you want to put on this aspect:)
The information is there, it is the most important.

How about the --sendping feature ? would you consider it ?

Thank you for your great app.

**Comment by garthvh** [comment]
The reply app was disabled by default as a spam risk as it is really just an example for developers on how to build their own module.
