### ISSUE TITLE
🐞 [Bug]: iOS App not displaying received messages

### ISSUE THREAD

**Issue by mzac** [meshtastic/Meshtastic-Apple#533]
### Firmware Version

2.2.23.5672e68

### What did you do?

Connected with iPhone and iPad to two seperate Heltec V3 units.  When I send messages from the iPhone to the iPad the message doesn't appear on the iPad but it does on the Heltec as a received message.  I see on the iPhone that the message has been acked. 

### Expected Behavior

Received messages should appear in the iOS app

### Current Behavior

Only sent messages are shown.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

iOS app version: 2.2.25

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ios-app-not-receiving-messages/10569/3

**Comment by AssetBurned** [comment]
+1 right after update from 2.2.24 to 2.2.25 no new message is shown.

**Comment by mzac** [comment]
2.2.26 was just released and fixes it
