### ISSUE TITLE
🐞 [Bug]: messages not appearing in the web app served from the device

### ISSUE THREAD

**Issue by sigtel** [meshtastic/Meshtastic-Apple#537]
### Firmware Version

2.2.23.5672e68 beta

### What did you do?

Received messages (general or directed) do not appear in the web app served by the node but do appear in the data via Python and on the device screen

### Expected Behavior

Received messages should appear in the web app

### Current Behavior

I can send messages via the web app but they are not acknowledged in the app. They do go out as I get replies but those replies only show on the node window and not in the web app (a similar issue was found with the iOS app but this now works since the update). The node is newly flashed. Using a simple Python script I can see all received data including any messages but these do not appear in the web app - the app is served directly from the node via browser access.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Yeah the web client is not really a fully featured messaging client.
