### ISSUE TITLE
🚀 [Feature Request]: Pressing on settings in a setting brings back to main setting screen

### ISSUE THREAD

**Issue by mzac** [meshtastic/Meshtastic-Apple#539]
### OS

iOS

### Description

If you are in a sub menu in the settings screen, for example in the MQTT config, pressing on the 'Settings' icon in the lower right should bring you back to the main settings screen.  I have seen other apps implement this feature.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aptonline** [comment]
Agreed, this is expected behaviour within most iOS apps that use this type of view.
