### ISSUE TITLE
Tapping notification doesn't take you to the correct thread

### ISSUE THREAD

**Issue by dmthepm** [meshtastic/Meshtastic-Apple#542]
### Firmware Version

2.2.25

### What did you do?

I get a notification when a new message comes and it opens the wrong channel or dm. 

This often leads me to quickly responding in the wrong thread thinking I am automatically in the right place.

### Expected Behavior

Tapping a notification would open the relevant channel or dm of that specific message.

### Current Behavior

Tapping a notification opens the app in whatever previous thread you had open. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/38
