### ISSUE TITLE
🚀 [Feature Request]: Disable auto correct on node search fields

### ISSUE THREAD

**Issue by tekstrand** [meshtastic/Meshtastic-Apple#547]
### OS

iOS, iPadOS, macOS

## Current Behavior
As a user, when searching for nodes, I often search for a node using just a few letters of the name. These short names are rarely recognized as real words by iOS, and will be auto corrected to other terms (e.g. `dd` becomes `Dr.`). When this auto correct happens, it changes the results, and causes the node I wanted to disappear. 

## Desired Behavior
As a user, I want to be able to search for any combination of characters in the nodes or messages(channels and DMs) screens without the OS auto correcting my query.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Fixed in 2.3.0
