### ISSUE TITLE
🚀 [Feature Request]: double-tap on bottom navigation buttons bring you to the "default" view of that page.

### ISSUE THREAD

**Issue by hatesyourface** [meshtastic/Meshtastic-Apple#549]
### OS

iOS, iPadOS, macOS

### Description

A double-tap on bottom navigation buttons bring you to the "default" view of that page.

Messages would bring you to the "Channel and Direct Messages" screen.
Bluetooth needs no changes
Nodes would bring you back to the top, with no search filter.
Map would re-center over the known nodes. 
Settings would bring you back to the top of the screen with the connected radio selected (if possible).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Maybe if apple updates the navigation at WWDC
