### ISSUE TITLE
🚀 [Feature Request]:  Wifi Connection between iPhone and Device

### ISSUE THREAD

**Issue by danielgrimard** [meshtastic/Meshtastic-Apple#550]
### OS

iOS

### Description

Can we have the option to connect to the hardware via Wi-Fi? I saw that this option is available on Android.
This feature will be helpful if we have one device and want to connect it to an MQTT server. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
You can use the MQTT client proxy to connect to a MQTT server, this would require a huge refactor for limited benefit, ESP32 wifi is unreliable and power intensive.  Not on my roadmap.

**Comment by danielgrimard** [comment]
Thanks for your answer.
And BTW, you guys are doing an excellent job for the Meshtastic Project.

**Comment by AssetBurned** [comment]
That is kind of a dup of https://github.com/meshtastic/Meshtastic-Apple/issues/506

**Comment by smiba** [comment]
Would greatly appreciate this, as it would mean I can use the Meshtastic app on MacOS and have it send me notifications. Bluetooth unfortunately does not have enough range, and does not support multi-client.
