### ISSUE TITLE
Crash on changing Device Role

### ISSUE THREAD

**Issue by fumpT** [meshtastic/Meshtastic-Apple#556]
### Firmware Version

2.3.0

### What did you do?

Pressing Save after changing Device Role from client hidden to client crashes app. 

### Expected Behavior

Configuration should be applied to the node.

### Current Behavior

App crashes to Home Screen.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

iPhone 15 Pro Max on iOS 17.4

**Comment by garthvh** [comment]
Your app is out of date

**Comment by garthvh** [comment]
This should be fixed in 2.3.1
