### ISSUE TITLE
🐞 [Bug]: PAX Module name in settings [Test Flight v2.3.2 (875)]

### ISSUE THREAD

**Issue by AeroXuk** [meshtastic/Meshtastic-Apple#568]
### Firmware Version

N/A

### What did you do?

Go to Settings.
Scroll to Module Configuration.
PAX Counter is displayed as `config.module.paxcounter.settings`.

### Expected Behavior

Should probably be displayed as `PAX Counter`.

### Current Behavior

Displayed as `config.module.paxcounter.settings`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AeroXuk** [comment]
Still present in the just published Test Flight v2.3.2 (875).

**Comment by garthvh** [comment]
What language?

**Comment by AeroXuk** [comment]
English (UK). Looks like (876) fixes this.
