### ISSUE TITLE
🚀 [Feature Request]: Show channel name in regular way

### ISSUE THREAD

**Issue by lucidnx** [meshtastic/Meshtastic-Apple#569]
### OS

iOS

### Description

Hello! My friends found it to be misleading to show whole channel name with uppercase letters and spacing after each. It's not clear how it should look and it may cause "user" errors. It's rather annoying than looking good. Can you please change these channel names to be shown in the normal way? Especially when it's case sensitive and used to identify channels.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
If you camel case your name it will display it as words
