### ISSUE TITLE
🚀 [Feature Request]: Match features/functions with Android app

### ISSUE THREAD

**Issue by lucidnx** [meshtastic/Meshtastic-Apple#570]
### OS

iOS, iPadOS, macOS

### Description

Hello! I would like to see identical features in both apps, maybe in desktop management client too, can you cooperate with Android devs to bring features from there to iOS app and opposite?
Some kind of cooperation would be nice and help people aswell.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
There are complely different codebases written by different developers, they are never going to be exactly the same.

There is a project to collaborate cross platform here: https://github.com/orgs/meshtastic/projects/16
