### ISSUE TITLE
🐞 [Bug]: Waypoint deletion swaps coordinates and doesn't expire directly

### ISSUE THREAD

**Issue by jurriaan** [meshtastic/Meshtastic-Apple#572]
### Firmware Version

v2.3.2.63df972

### What did you do?

I noticed some inconsistency in meshtastic packets when manually decoding some Waypoint messages received from iOS devices.

On waypoint deletion I saw that the longitude and latitude where swapped in the message and the expiry isn't immediate.

### Expected Behavior

I would expect that the longitude and latitude stay valid in the deletion message, and that the expiry is immediate when waypoints are deleted for everyone.

### Current Behavior

The longitude and latitude are swapped:
https://github.com/meshtastic/Meshtastic-Apple/blob/b05b595499631e456c2a150d488bf027c1720f8b/Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift#L206-L207

The expiry is set to 8 hours from now:
https://github.com/meshtastic/Meshtastic-Apple/blob/b05b595499631e456c2a150d488bf027c1720f8b/Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift#L26-L27
https://github.com/meshtastic/Meshtastic-Apple/blob/b05b595499631e456c2a150d488bf027c1720f8b/Meshtastic/Views/Nodes/Helpers/Map/WaypointForm.swift#L219-L220

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I think this isn't intended behavior.

This is how the Android app handles it:

https://github.com/meshtastic/Meshtastic-Android/blob/61be6e9985a0609423b62ff77ad7c2bc6684d61b/app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt#L257-L259

**Comment by garthvh** [comment]
In app review, fixed by https://github.com/meshtastic/Meshtastic-Apple/pull/584
