### ISSUE TITLE
🚀 [Feature Request]: Ability to connect other Nodes via DeepLinking or Scanning QR Code.

### ISSUE THREAD

**Issue by AakifNadeem** [meshtastic/Meshtastic-Apple#578]
### OS

iOS

### Description

For now, we are unable to scan QR from other iPhones connected to another node (Just like there is a scan QR option in Android). Also, the app is not connected via deeplink when we are opening the shared QR Code link.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
You scan the QR code from the camera

**Comment by AakifNadeem** [comment]
@garthvh when scanning from camera I get this screen on browser.

![Meshtastic Channel Settings  Meshtastic](https://github.com/meshtastic/Meshtastic-Apple/assets/58801997/c59f9e6b-4c1d-400b-bbf2-c938aabd9404)

**Comment by garthvh** [comment]
You may need to reboot your phone, the url is registered with apple and opens the app automatically
