### ISSUE TITLE
🚀 [Feature Request]: MQTT logging / viewing on settings screen

### ISSUE THREAD

**Issue by jaydarkseed757** [meshtastic/Meshtastic-Apple#580]
### OS

iOS, iPadOS, macOS

### Description

Trouble shooting MQTT can be difficult if you don't have a serial console around. If there was a way to enable a log view in settings on device, you could see some of the things like publishing to the MQTT topic and reads from that topic. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
With the client proxy I don't really do any mqtt in the app, there is not a lot of data logged.  There is a update in TestFlight to improve the status icons

**Comment by garthvh** [comment]
In app review connection errors will show on the mqtt config view by https://github.com/meshtastic/Meshtastic-Apple/pull/584
