### ISSUE TITLE
🚀 [Feature Request]: Add possibility to set the Timezone info on the node

### ISSUE THREAD

**Issue by caveman99** [meshtastic/Meshtastic-Apple#590]
### OS

iOS, iPadOS, macOS

### Description

Recently the time display on the firmware screen (and logfile) for the node was made aware of timezones. Please add the ability to set via config.device.tzdef. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The required format is the raw timezone description. Added bonus would be for the user to be able to select a more legible format  from a dropdown. A translation table can be found on this link: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv

**Comment by garthvh** [comment]
That seems bad, I need UTC in the app.

**Comment by garthvh** [comment]
I don't want to manage it at all, apple is way better at this than me or the posix solution.

This is in TestFlight under device config, it builds the value from your timezone.

**Comment by caveman99** [comment]
There may be more points where this needs to be taken into account, not many but I think I can find them. From the top of my head telemetry and Position values
 The current fix should correct Position timestamp.

**Comment by garthvh** [comment]
Yeah looks good here

**Comment by garthvh** [comment]
In app review, fixed by https://github.com/meshtastic/Meshtastic-Apple/pull/584
