### ISSUE TITLE
🚀 [Feature Request]: Notification when a new node is found

### ISSUE THREAD

**Issue by jclagreca** [meshtastic/Meshtastic-Apple#591]
### OS

iOS, iPadOS, macOS

### Description

Would be great to get a push notification on the app when a new node is detected.  This would be very useful for war driving scenarios, or just to know when a new user was around.  

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
> Also, we'll want to make this behavior an opt-in via an App setting, as there are large MQTT based meshes that would blow up user's push notifications.

I added a settings bundle so we can put a bunch of notification settings in the root app settings panel.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/593

Waiting for test flight approval
