### ISSUE TITLE
🐞 [Bug]: 

### ISSUE THREAD

**Issue by jclagreca** [meshtastic/Meshtastic-Apple#595]
### Firmware Version

2.3.2

### What did you do?

When sending a message in the iOS app, sometimes the message compose does NOT get cleared like it should.  The message is sent, but also remains in the compose field.  Killing the app off and starting it again fixes it, until it starts doing it again.  

### Expected Behavior

After you send a message, it should automatically be removed from the message compose section.  

### Current Behavior

When the bug occurs, the message stays in the compose window, even after the message is sent.  

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by senditron2000** [comment]
Experienced this also.
