### ISSUE TITLE
🚀 [Feature Request]: UI - Tab brings back to tabs home 

### ISSUE THREAD

**Issue by eb2ai** [meshtastic/Meshtastic-Apple#600]
### OS

iOS, iPadOS, macOS

### Description

I think it's pretty standard IOS behavior that when you click the tab while in the tab it brings you back to that tab's home.

Example.

1. If I navigate to Settings --> User I'm given the appropriate user config.
2. Click on messages I'm taken to messages.
3. If I then click on settings, I will go back to user config. (So Far so good)
4. If I then click on settings again, **it would be nice to bring me to the home of settings.**

This is common beha

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Maybe if there are navigation updates at wedc
