### ISSUE TITLE
🚀 [Feature Request]: Display uptime (seconds) in the UI

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Apple#603]
### OS

iOS, iPadOS, macOS

### Description

In the device telemetry packet, we now have an uptime in seconds metric value that can be displayed in the clients to allow users to see how long a node has been running since the last boot.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Added to device metrics in TestFlight 2.3.5, awaiting app review
