### ISSUE TITLE
🚀 [Feature Request]: add Alert Bell for direct messages

### ISSUE THREAD

**Issue by jp83** [meshtastic/Meshtastic-Apple#604]
### OS

iOS

### Description

Request to add an alert bell icon button to the message input for sending direct messages to match the implementation of the channel message input.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Just to note I'm using this to trigger a relay as an external notification, alternatively maybe it would be nice to have a firmware setting to customize the triggering character to make it easier to send from other devices, but maybe that's a niche application and a gpio interface would eventually be better suited.

**Comment by garthvh** [comment]
Released in 2.3.6
