### ISSUE TITLE
(iPhone) Device metrics shifted to left, making batt% unreadable

### ISSUE THREAD

**Issue by MansM** [meshtastic/Meshtastic-Apple#605]
### Firmware Version

2.3.5

### What did you do?

go to nodes, select node, device metrics log

![IMG_9198](https://github.com/meshtastic/Meshtastic-Apple/assets/14215294/b66e4897-5084-4160-a5f9-75157246dd99)

### Expected Behavior

Readable battery percentage

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by purge98** [comment]
Uptime is always 0s.

**Comment by thebentern** [comment]
> Uptime is always 0s.

You need to update to the latest firmware alpha to report uptime. It was just added last week.

**Comment by paoloponzano** [comment]
This happens for me too

**Comment by purge98** [comment]
The node map restriction distance is too limited. I live over 5500 kms from NZ. Please allow up to 16,000 kms so I can see the whole world. Why the limitation?

**Comment by MansM** [comment]
Can you guys make separate issues for your issues, helps maintainers to be able to close fixed issues. 

And me getting notifications for the additional comments.

**Comment by garthvh** [comment]
Released in 2.3.6
