### ISSUE TITLE
🚀 [Feature Request]: Custom Logo & Text

### ISSUE THREAD

**Issue by Adrelien** [meshtastic/Meshtastic-Apple#606]
### OS

iOS

### Description

Simple place to customize Meshtastic logo to a custom png :) 

- Helps users personalize their nodes
- It can be used for teams to identify nodes
- It can be used to put contact information in case the user lost their node or forgot it somewhere 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The OEM tool is available for this
