### ISSUE TITLE
🐞 [Bug]: IOS Node filter defaults to via MQTT on app restart

### ISSUE THREAD

**Issue by rustycoon** [meshtastic/Meshtastic-Apple#607]
### Firmware Version

2.3.4 (900)

### What did you do?

Selected node filter with menu icon on lower right of node list. Made selections to turn off MQTT. Hard restarted app (swipe up). Checked node filter again.

### Expected Behavior

Would expect previous selections to remain.

### Current Behavior

Went to node filter again and previously selections dont persist. Only via Lora and via MQTT are selected on automatically. Multiple tries on 2.3.4 and 2.3.3 iOS app updated today 4/17/24 with iOS 17.4.1.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Thank you

**Comment by garthvh** [comment]
The filters are not persistent.

**Comment by scottrhoyt** [comment]
Would we like to make these persistent? I'm looking to do some contributions and this could be a good ramp up task. I'm assuming we'd want to persist these in CoreData--though I could see a case for a simple plist for something like this as well?

**Comment by garthvh** [comment]
So far the consensus has been no change n the filters

**Comment by garthvh** [comment]
> Would we like to make these persistent? I'm looking to do some contributions and this could be a good ramp up task. I'm assuming we'd want to persist these in CoreData--though I could see a case for a simple plist for something like this as well?

There is plenty to do though, some issues are tagged with good first issue, let me know what you are interested in I can point you to interesting things to do.
