### ISSUE TITLE
🚀 [Feature Request]: do not use modal window when sending traceroute

### ISSUE THREAD

**Issue by akohlsmith** [meshtastic/Meshtastic-Apple#608]
### OS

macOS

### Description

every time you two-finger tap and send a traceroute a modal window pops up saying it was sent and it'll take a while. This is very irritating and doesn't really help much. The proposed solution is to just not do that.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Trace routes are expensive, this is on purpose.
