### ISSUE TITLE
🚀 [Feature Request]: 

### ISSUE THREAD

**Issue by callieschneider** [meshtastic/Meshtastic-Apple#610]
### OS

iOS

### Description
This feature request seeks to enhance the navigation experience within the Meshtastic app by improving the functionality of the menu items located at the bottom of the interface. These items include Messages, Bluetooth, Nodes, Mesh Map, and Settings. The goal is to simplify the process of navigating back through various menu hierarchies by allowing users to tap the same menu icon again to return to the previous screen or to quickly reset to the main screen of that section by double-tapping.

### Objective:
To streamline and expedite navigation within the Meshtastic app, making it more intuitive and efficient for users to move between different levels of menu hierarchies without relying on traditional "back" buttons or other navigational elements.

### Proposed Enhancements:

1. **Toggle Navigation:** Introduce functionality where tapping a bottom menu icon (e.g., Messages, Nodes, Settings) toggles the user back to the previous menu level. This would work recursively until reaching the main screen of each menu item.

2. **Double-Tap Reset:** Allow users to double-tap the currently active bottom navigation icon to instantly return to the main screen of that particular function. This quick reset helps users quickly exit from deep menu levels without multiple taps.

### Benefits:

- **Efficiency:** Reduces the number of taps required to navigate through the app, thereby speeding up the interaction process and making the app more responsive.
  
- **Intuitiveness:** Enhances the user experience by aligning with common navigation patterns found in many popular applications, thus making the navigation process more intuitive.
  
- **Quick Reset:** Enhances the functionality of the navigation bar by allowing a rapid return to the starting point of each section, facilitating smoother transitions for users.

This enhancement would significantly improve the usability of the Meshtastic app by making navigation smoother and less disruptive, especially during complex interactions within the app's diverse functionalities. While iOS is selected for this feature request, it could be applied to iPadOS and macOS as well.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The double tap behavior is entirely custom and not on the roadmap
