### ISSUE TITLE
🚀 [Feature Request]: 

### ISSUE THREAD

**Issue by callieschneider** [meshtastic/Meshtastic-Apple#611]
### OS

iOS

### Description

**Description:**  
This feature request seeks to enhance the accessibility and usability of node information within the Meshtastic app. The proposal is to allow users to access detailed node information from anywhere in the app where node icons are displayed, by implementing a long-press action on the node’s icon. Additionally, where a long-press already triggers an action, an option to navigate to the node's detailed information in the nodes tab should be added to the existing menu.

**Objective:**  
To streamline the process of accessing detailed node information, making it more intuitive and faster, thereby improving user experience by reducing the number of steps needed to access this information from various parts of the app.

**Proposed Enhancements:**

1. **Long-Press to Access Node Info:** Introduce or enhance the long-press gesture on node icons across the app, allowing users to quickly access a detailed node information screen. This would be implemented on all screens where node icons are visible, including the map and various lists.

2. **Enhanced Menu Options:** For contexts where a long-press already presents a menu, add an option that directs users to the node’s detailed information within the nodes tab. This ensures consistency and ease of access without disrupting existing functionalities.

3. **Intuitive Navigation Back to Previous Window:** Provide multiple methods to return to the previous window after viewing node information, such as swiping, pressing a top-left back button, or tapping the relevant section icon at the bottom (e.g., Messages, Map). This would allow users to seamlessly return to their previous context.

**Benefits:**

- **Efficiency:** Allows quicker access to detailed node information, reducing navigation complexity and the time taken to reach essential data.

- **Consistency:** Integrates seamlessly with existing UI gestures (like long-press and swipe), maintaining a consistent user interface experience across the app.

- **Enhanced User Experience:** Provides a smoother and more intuitive navigation pathway for users, enhancing overall satisfaction with the app usability.

- **Accessibility:** Makes it easier for users to access information without needing to remember the specific location of node details, facilitating a more inclusive user interaction model.

By implementing these enhancements, the Meshtastic app would significantly improve its usability, making it easier and more efficient for users to interact with node data across various parts of the application. This could apply to iPadOS, and macOS as a right-click, or double-click.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The status bar in swiftUI is the way to handle the scroll to top functionality in SwiftUI at this point, there were not updates to this a WWDC.  Probably won't be managing a custom navigation system.
