### ISSUE TITLE
🐞 [Bug]: Node list is not updating properly

### ISSUE THREAD

**Issue by jclagreca** [meshtastic/Meshtastic-Apple#613]
### Firmware Version

latest non alpha

### What did you do?

Often times I will look at the node list, and see a node has a moon next to it, and that it hasn't checked in for a while.  BUT, I can send a traceroute to it, and get an immediate response.  Which means that it IS up and running.  If I simply close the meshtastic mac app, and relaunch it, the app then reflects properly.  This happens fairly often that I have to close the app and relaunch it to show me accurate information.  

### Expected Behavior

to show me up to date info

### Current Behavior

doesn't show me up to date info unless i restart the app

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The last heard time comes over the mesh, the moon indicates activity in the last 15 minutes.
