### ISSUE TITLE
🚀 [Feature Request]: Notification settings per channel/type

### ISSUE THREAD

**Issue by tekstrand** [meshtastic/Meshtastic-Apple#616]
### OS

iOS, iPadOS, macOS

### Description

It would be neat to be able to subscribe to notifications for one channel but not another, or DMs but no channels. What made me think of this is an extremely busy Default/Long Fast channel where tons of people are just saying "copy" while I am having a separate conversation that I do actually want notifications for.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tekstrand** [comment]
@garthvh let me know why this one is a bad idea ;)

**Comment by garthvh** [comment]
You can mute DMs, doing it for channels is harder as they get deleted and re-added on every connect, so I had to remove it, I would like it back.

**Comment by garthvh** [comment]
@tekstrand I think I could do it if we added mute here https://github.com/meshtastic/protobufs/blob/eade2c6befb65a9c46c5d28ae1e8e24c37a1a3d0/meshtastic/channel.proto#L94

**Comment by tekstrand** [comment]
Oh good point RE: location precision on the module. Right up the same alley. If you'd like me to help, let me know how!

**Comment by garthvh** [comment]
We need a protobufs issue

**Comment by tekstrand** [comment]
So quick! I stepped away for a few days and it's already in alpha!
