### ISSUE TITLE
🐞 [Bug]: Meshtastic Leaks Precise Location from Imprecise Secondary Channel

### ISSUE THREAD

**Issue by Coopersmith-24601** [meshtastic/Meshtastic-Apple#617]
### Firmware Version

2.3.6.7a3570a

### What did you do?

I believe I’ve found a bug which allows the precise location of one device to be sent to another even though less than precise settings are being used.

  I reported this several weeks ago after seeing precise locations on a device which should not have been able to see the precise location of a second node, but at that time I was unable to describe the conditions which can cause this to happen in a repeatable method to the dev team.  

I now have a method which is reproducible.

  The demonstration requires two different nodes and for the purposes of this test I am using version 2.3.6 Alpha software, but be aware this issue seemed to have existed as far back as  2.3.3 as well.  

Node A is a RAK 4631 connected via BLE to a MacBook Air running Meshtastic Version 2.3.5 (911).
 Node B is a Heltec v3 connected via BLE to an iPhone running Meshtastic Version 2.3.5 (911)  

On Node A, two channels were set up.  The Primary is running default settings, but with precision diluted to 1.8 miles.  The Secondary is encrypted with a 256 bit key, and its precision diluted to 1.8 miles.  The QR code for channel settings for Node A was then shared with Node B.

On Node B, on both the Primary and Secondary precision is then set to be diluted to 0.9 miles.

  In the interest of time for this demonstration, the Node B location is set to be shared every 30 seconds from the iPhone app App Settings and 30 seconds in the Position Module.

  NOTE:  MQTT is switched off in both upload and download mode on both devices.  The result of this when looking at the app on the MacBook’s Meshtastic app is illustrated below, but results may vary depending on your location.
  
![image](https://github.com/meshtastic/Meshtastic-Apple/assets/167914673/27bf92bd-3c8c-4da2-84a2-e3df840a86e9)

Node A is represented by the COOP and green circle.

Node B is represented by the CMBL and purple circle.

(SACC is an incidental 3rd party.)  

Once that is complete, a text message is sent from the Secondary channel of Node B to Node A to confirm normal text transmission.

The set up for testing is complete.

To conduct the test, on the Secondary channel of the iPhone app for Node B, share the location of Node B.

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/167914673/52a69ca3-b680-4682-b272-a253f63aac8c)

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/167914673/f4c03366-19c2-48e3-8b81-e3226139c73d)

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/167914673/1e1ffe63-5710-4952-9f45-cf057708faff)

Then look at the results of the app connected to Node A, the MacBook.  

You can examine Node B’s location as delivered to Node A and you will find a properly drawn circle indicating an imprecise location, but the center of the circle will be at the precise location of Node B and it’s iPhone.  This will show up in the Node’s individual map view as well as in the overall MeshMap view of the MacBook until the iPhone’s Meshtastic app refreshes its location.

As you recall we previously set the Meshtastic app on the iPhone to update in 30 second intervals here for testing purposes and you can see this behavior, so the results you get may vary depending on exactly when in the cycle you’ve sent the location over the Secondary channel.  

I am hesitant to show the actual results from my location here on the internet, but can provide them to any researcher who contacts me with further questions.

  I do not know if this location data which has been passed via the Secondary channel is held and passed on farther to the MQTT database or local Mesh Network, but the simple fact it does somehow get passed from iPhone to Node B, through Secondary, to Node A and is displayed there precisely is troubling.

  It should also be noted a similar behavior exists on the Chrome Meshtastic Web app if used for Node A and while that app is not displaying any nodes exactly correct, it’s still troubling the precise location data appears to be sending to it.

### Expected Behavior

Sharing a location from any channel SHOULD NOT in any way ever send the location in anything other than that channel's defined precision.

### Current Behavior

Sharing location from a Secondary channel with a less than precise location sends the precise location to the other user.  Although the second user's device will draw an imprecise location circle, the center of that circle and the Node ID sent will appear in the precise location of the first user.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by daviesgeek** [comment]
I seem to be able to reproduce this as well. Primary channel seems to work fine to set imprecise location, but the secondary channel does not; it sends the exact location but marks it as imprecise, so while it shows up with a circle on the app and the web maps like meshmap or Liam Cottle's map, the center of the circle is my exact location

**Comment by garthvh** [comment]
All the send position functions look up the channel and use the precision settings.

**Comment by garthvh** [comment]
@jp-bennett the positions appear to have the position precision value set but the coordinates are not getting reduced, the same message sending function is working when the positions are sent with the timer

**Comment by jp-bennett** [comment]
I think getPositionFromPhoneGPS() is building the whole packet, and the device firmware is just forwarding it through as it's written. So the two code branches in getPositionFromPhoneGPS() would need to also do the position dilution steps.

**Comment by garthvh** [comment]
The firmware has been updated, pins send in DMs will still be sent out with full precision, but broadcast positions will use the channels position precision from the firmware.
