### ISSUE TITLE
🐞 [Bug]: Typo under Firmware Updates

### ISSUE THREAD

**Issue by Zmk55** [meshtastic/Meshtastic-Apple#618]
### Firmware Version

2.3.6

### What did you do?

I was navigating the settings menu of the Meshtastic iOS application when I accessed the  Firmware Updates section and noticed a typo in the last sentence.  

 "ESP 32 OTA update is a work in progress, click the button below to **sent** your device a reboot into ota admin message." 

### Expected Behavior

The word "sent" should be "send." So, the corrected sentence would be:

"ESP 32 OTA update is a work in progress, click the button below to send your device a reboot into ota admin message."

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by RCGV1** [comment]
https://github.com/meshtastic/Meshtastic-Apple/pull/620
