### ISSUE TITLE
🚀 [Feature Request]: able to select which channel to use when DM’ing a node

### ISSUE THREAD

**Issue by MansM** [meshtastic/Meshtastic-Apple#628]
### OS

iOS

### Description

When I have multiple channels ( 0: Primary Channel (longfast), 1: Secondary (with my own psk)) I would like to be able to select which encryption to be used with that node.

I can do this with python-cli but haven’t seen it in iOS, iPadOS or macOS. Best location would be in DM screen or Node detail screen. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This is managed by the firmware.
