### ISSUE TITLE
🐞 [Bug]: Settings > User > Call Sign issues

### ISSUE THREAD

**Issue by gitToad** [meshtastic/Meshtastic-Apple#629]
### Firmware Version

2.3.6 (917)

### What did you do?

Mac App 2.3.6 (917) : Settings > User > Call Sign
try to edit call sign

### Expected Behavior

1. now only allows short names (used to be more, shame to lose the extra letters for descriptive names and need to update node names / docs for people now...)

2. says it can be up to 8 bytes long. Actually only allows 6

3. perhaps "8 characters long" is more user friendly than "8 bytes long" (detail) ?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
8 bytes is not 8 characters, long name is used for call sign short name is only 5 bytes

**Comment by garthvh** [comment]
It was restricted to 6 bytes, which is less than six characters, it has been updated to allow 8 bytes
