### ISSUE TITLE
🚀 [Feature Request]: Add state to suggested communities where applicable/available

### ISSUE THREAD

**Issue by daviesgeek** [meshtastic/Meshtastic-Apple#630]
### OS

iOS, iPadOS, macOS

### Description

When suggesting MQTT topics in the client, the state should probably be added so as to further break up mqtt topics by region.

Talked about this earlier and I haven't had a chance to implement it, but I'd like to not lose this: https://discord.com/channels/867578229534359593/874835141145542716/1227680104709357569

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
I did this in the latest release

**Comment by daviesgeek** [comment]
Ahhh i think my mac app wasn't up to date and I missed this! thanks :D
