### ISSUE TITLE
🐞 [Bug]: Waypoint Default Duration

### ISSUE THREAD

**Issue by Coopersmith-24601** [meshtastic/Meshtastic-Apple#634]
### Firmware Version

2.3.8.d490a33

### What did you do?

Noticed a Waypoint dropped on the Map.  Noticed the expiration date on the Waypoint is 14 years from now.  Believe this is probably a result of the defaults on Waypoints to not expire.
<img width="549" alt="Screenshot 2024-05-06 at 5 33 41 PM" src="https://github.com/meshtastic/Meshtastic-Apple/assets/167914673/0a423e1c-e37e-4cee-8ea3-35a9def5d8b2">

### Expected Behavior

Default should probably be set to expire in a much shorter time such as 24 or 48 hours do avoid old and irrelevant Waypoints to continue in databases for over a decade.  If somebody wants to intentionally set a Waypoint for long than a week, there should probably be a confirmation dialogue to discourage that behavior.

### Current Behavior

Currently the default for Waypoints is to not expire.  This is almost certainly not a great idea.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is just based on my experience with player created content in general and how if something can be abused it almost certainly will be.  Setting a shorter default time will help minimize the impacts of turf wars and jerk-like behavior.

**Comment by garthvh** [comment]
The default for waypoints is not to expire and have a null expire date.  The map is not displaying the protobuf properly.
