### ISSUE TITLE
🚀 [Feature Request]: Disable MQTT downlink for LongFast + default key

### ISSUE THREAD

**Issue by daviesgeek** [meshtastic/Meshtastic-Apple#638]
### OS

iOS, iPadOS, macOS

### Description

This is more of an open discussion around implementing this feature, but I am suggesting that downlink is entirely disabled on LongFast + default key. There's a huge potential to have issues with taking down an entire network with an accidental flip of a switch.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by b8b8** [comment]
https://github.com/meshtastic/rfcs/pull/9#issuecomment-2051701231

**Comment by daviesgeek** [comment]
@b8b8 thanks, closing this in favor of that RFC
