### ISSUE TITLE
🐞 [Bug]: can`t connect to more than one device

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Apple#640]
### Firmware Version

2.3.8

### What did you do?

the ios app is not able to connect to more than one device in my case

### Expected Behavior

be able to connect to more than one single device

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Swipe left to disconnect

**Comment by cracky22** [comment]
oh thanks :)
