### ISSUE TITLE
🐞 [Bug]: Sharing location from app to device does not work since settings module update

### ISSUE THREAD

**Issue by hutchisr** [meshtastic/Meshtastic-Apple#646]
### Firmware Version

2.3.9

### What did you do?

Enabled share location in App Settings, set "Not Present" in Location device settings.

### Expected Behavior

* (case 1) When Share Location is enabled, the device should report its position as the location reported from the device.
* (case 2) When using "Fixed Position" in device location settings, the device should obtain a position from the app and subsequently report it as the device's position.

### Current Behavior

* (case 1) The device never broadcasts a position to the mesh
* (case 2) Same as above, the device never broadcasts a position.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paoloponzano** [comment]
Same
