### ISSUE TITLE
🐞 [Bug]: BT no longer reconnects automatically in background 

### ISSUE THREAD

**Issue by miweber67** [meshtastic/Meshtastic-Apple#649]
### Firmware Version

2.3.7

### What did you do?

Since updating the app to 2.3.8, it no longer automatically reconnects to my node when I come back in to range. It used to work fine; no change in node firmware. This results in long periods of missing device metric data. I also noticed the app had a really hard time connecting to the node right after the update. 

### Expected Behavior

App should reconnect to the node when phone is brought back in range of BT.  

### Current Behavior

App does not reconnect to node automatically. I have to open the app and click on the node to reconnect it. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
No BLE connection code has changed
