### ISSUE TITLE
🐞 [Bug]: Clearing position log disables history past the most recent point

### ISSUE THREAD

**Issue by pdelbarba** [meshtastic/Meshtastic-Apple#650]
### Firmware Version

2.3.6.7a3570a Beta

### What did you do?

Nodes -> Position Log -> Clear
All position logs will be deleted
At next broadcast, a point will be added to the log, but on each subsequent packet the listed point will be replaced instead of a new one being added

If you go into Mesh Map -> 'i' -> Node History (which will still show as 'on') and turn it off, then on again, points begin to be listed as expected

### Expected Behavior

Deleting points should have no impact on whether points are logged afterward

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The Node History setting seems to be related, I repeatedly worked around the issue by toggling it, nothing else seems to cause positions to log again, including restarting the app.

**Comment by garthvh** [comment]
If you position is essentially the same as the last one it will be replaced not added, if you have reduced precision on it saves just one log entry
