### ISSUE TITLE
🚀 [Feature Request]: Add time to messages

### ISSUE THREAD

**Issue by commanderts** [meshtastic/Meshtastic-Apple#651]
### OS

iOS, iPadOS, macOS

### Description

It would be nice to add the send time next to messages. In the channel overview I see the timestamp of the last message, if I view the channel no times are shown. (I know I can see the time in message details)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
There is time on both message lists and in the message details for each message.
