### ISSUE TITLE
🐞 [Bug]: iOS can’t delete MQTT node from db

### ISSUE THREAD

**Issue by SpudGunMan** [meshtastic/Meshtastic-Apple#668]
### Firmware Version

2.3.11.2740alpha 

### What did you do?

Video of issue shown in discord but replicate by trying to delete a node of type MQTT (not LORA) and you can’t 

### Expected Behavior

Expect ability to delete MQTT nodes from db by swipe delete node and confirm delete 

### Current Behavior

The node isn’t deleted (nothing happens after confirming delete) 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SpudGunMan** [comment]
Rolled back to an older version went with 2.3.7(932) and was able to delete

**Comment by garthvh** [comment]
Can't replicate this
