### ISSUE TITLE
🐞 [Bug]:  MacOS Meshtastic app getting unreadable node list after a few hours. 

### ISSUE THREAD

**Issue by rvenes** [meshtastic/Meshtastic-Apple#673]
### Firmware Version

MacOS 14.5 Meshtastic 2.3.9 (948)

### What did you do?

Open the app and let it sit for a few hours.

Problem with the Meshtastic app on MacOS.  After a while (few hours) the app node list becomes unreadable (look at pictures) The app also slows down, takes several seconds to change views in the app.  There is not many nodes around me, only 13. 
Feels also like its getting worse if the Device metric log and position log is huge (over 1000 lines).  
It helps to restart the app, but getting unreadable after a few hours when i leave it open.  

![image](https://github.com/meshtastic/Meshtastic-Apple/assets/95510707/171e4da3-39c7-468e-b86d-51bdc59ef764)
![image](https://github.com/meshtastic/Meshtastic-Apple/assets/95510707/8bee3884-3177-4c4e-b9fd-b79f598b1164)
![image](https://github.com/meshtastic/Meshtastic-Apple/assets/95510707/5c124825-d57c-4ea7-8204-499c678d4db5)

### Expected Behavior

Not getting unreadable

### Current Behavior

uh... well. its just getting worse the longer you have the app open. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Works fine on iPhone from the same nodes.

**Comment by garthvh** [comment]
Probably Intel Mac related, can't replicate.
