### ISSUE TITLE
🐞 [Bug]: Newer Packets than Displayed Last Heard Date/Time

### ISSUE THREAD

**Issue by pqhf5kd** [meshtastic/Meshtastic-Apple#676]
### Firmware Version

2.3.10

### What did you do?

1) Known node, with position and device metric logs, goes offline. 
2) Client app is relaunched
3) Node's last heard date/time is older than the newest packet in position/metrics log

### Expected Behavior

Last heard should always reflect the latest packet received

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I can still see this issue with one node, trying to recreate with additional nodes

**Comment by garthvh** [comment]
All of the time is managed by time firmware.
