### ISSUE TITLE
[Feature Request] support connecting to multiple nodes from the iOS app

### ISSUE THREAD

**Issue by 72A12F4E** [meshtastic/Meshtastic-Apple#679]
### OS

iOS, iPadOS, macOS

### Description

https://github.com/meshtastic/Meshtastic-Android/pull/1078

Do this for the Apple apps

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by pqhf5kd** [comment]
Could the data for each node be shared between client devices over iCloud? 

Use case: connecting to portable node from macOS at one location. Later connecting the same node to iPhone, retaining nodeDB, metrics and messages.

**Comment by 72A12F4E** [comment]
> Could the data for each node be shared between client devices over iCloud?
> 
> Use case: connecting to portable node from macOS at one location. Later connecting the same node to iPhone, retaining nodeDB, metrics and messages.

This should be possible via CloudKit, but we might want to restrict certain data from syncing depending on how that might impact the UX. Would need to think about that more.

**Comment by garthvh** [comment]
A backup and restore of the data from a previously connected node could work, displaying multiple users at once from changing perspectives is not a direction I want to go.

**Comment by pqhf5kd** [comment]
@garthvh I'm not sure if you're responding to my suggestion, or @72A12F4E's original suggestion.

Please can you clarify 'displaying multiple users at once from changing perspectives'

**Comment by garthvh** [comment]
The phone to user in meshtastic is 1:1, you can have different users with different channels and keys that display at the same time.  You don't log into what's app as two users at the same time.
