### ISSUE TITLE
🚀 [Feature Request]: Calculate and Display True Bearing of Nodes

### ISSUE THREAD

**Issue by pqhf5kd** [meshtastic/Meshtastic-Apple#680]
### OS

iOS, iPadOS, macOS

### Description

Calculate the true bearing (angle between yourself and other nodes, from North) and display in various views next to distance. 

The math is in the [Android code.](https://github.com/meshtastic/Meshtastic-Android/blob/5b3c78316b8accc789471f7ebdcd36e295c76682/app/src/main/java/com/geeksville/mesh/util/LocationUtils.kt#L217)

example: 
<img width="247" alt="Screenshot 2024-06-08 at 17 23 06" src="https://github.com/meshtastic/Meshtastic-Apple/assets/20027419/045d6158-9caf-4b3c-bf8d-8c129a321b60">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
What is the real use case for true bearings? Is there a lot of surveying or meshtastic aircraft use?  Not sure it is really relevant for most users.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/843

**Comment by garthvh** [comment]
![IMG_3013](https://github.com/user-attachments/assets/58ab8ed0-a42c-4ff5-95a1-e613a0f35787)
