### ISSUE TITLE
iOS 18 support

### ISSUE THREAD

**Issue by paoloponzano** [meshtastic/Meshtastic-Apple#688]
### Firmware Version

2.3.11

### What did you do?

iOS 18 dev beta 1 was released yesterday and I had a chance to test the Meshtastic app. I know it’s just the first beta but I think it would be good to keep track of the issues to solve them before stable release is published.

### Expected Behavior

Open the messages page, select any channel. 
The expected behavior is for the app to show the channel chat and text input box. 

### Current Behavior

After opening the channel, a blank page is shown. The chat won’t load even after waiting some minutes
![IMG_5452](https://github.com/meshtastic/Meshtastic-Apple/assets/24962679/ac986969-3d90-488f-80fe-57dafb754c65)
![IMG_5453](https://github.com/meshtastic/Meshtastic-Apple/assets/24962679/42ef79d1-be36-41d0-98a8-5bc8b9db6684)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments
I tried deleting app’s data, but that didn’t fix it.
I’m not sure if I could take some logs without a Mac, but I could try in the coming weeks installing a VM with macOS to run xcode 
I will update this report if I find other issues related to the update

**Comment by runestone74** [comment]
It seems like a new Bluetooth allow switch is needed in the app settings for ios to be able to connect. I got a connection at first but after a reboot the Meshtastic client seems to have lost BT privileges

**Comment by garthvh** [comment]
Maybe in a month once there is a build, one day in is too soon
