### ISSUE TITLE
🐞 [Bug]: Build Instructions Incomplete

### ISSUE THREAD

**Issue by kalanihelekunihi** [meshtastic/Meshtastic-Apple#689]
### Firmware Version

2.3.11

### What did you do?

I have checked out the Meshtastic-Apple branch, with the intention of fixing some bugs with the Settings menu, where there are some accessibility issues. For example, some of the fields are improperly labeled, preventing their use within VoiceOver and VoiceControl, and the interactive animations apply to 1 element below where the user actually touches. Among others...

So, I checked out the branch, and attempted to follow the steps under README.md, namely:

```sh
git clone git@github.com:meshtastic/Meshtastic-Apple.git
cd Meshtastic-Apple
open Meshtastic.xcodeproj
```

However, doing so, there are a number of missing dependencies, which are likely related to missing steps.

First, there is the submodule `protobufs` is not included in the checkout command, because git clone was missing the flag: --recurse-submodules

Second, the developer requires the "com.apple.developer.carplay-communication" entitlement on their Developer account to properly sign the application. If they do not do this separately through the Apple Developer Program website, they will be unable to notarize the application - therefore preventing builds from proceeding.

Third: it appears that there are 3 missing build dependencies: SQLite, CocoaMQTT, and SwiftProtobuf
These were not included in `.scripts/gen_protos.sh`

I would ask that the README.md be updated to include these missing dependencies, and if need be their minimum and maximum expected versions.

### Expected Behavior

When following the provided documentation, one would be able to build the project file.

### Current Behavior

Attempting to build gives multiple missing dependency errors.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This is in progress, part is in the current active pull.  We are also in the process of switching to an organizational account, you have to be a member of the development team to have all the entitlements
