### ISSUE TITLE
🐞 [Bug]: Setting GPS location on a node doesn't work all the time

### ISSUE THREAD

**Issue by 72A12F4E** [meshtastic/Meshtastic-Apple#695]
### Firmware Version

2.3.11

### What did you do?

Turning GPS to disabled in the position settings menu, setting a fixed position, then turning GPS to enabled..

### Expected Behavior

I'd expect the behavior to either be that the Fixed Position toggle overrides the GPS Enabled setting with the toggle remaining visible and a note warning the user that Fixed Position takes precedence -or- enabling GPS would automatically disable Fixed Position.

### Current Behavior

* Hides the Fixed Position toggle and the ability to disable it.
* Does not enable GPS location reporting despite it showing as enabled.
* Leaves the node showing Fixed Position Mode enabled on the node display.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The only issue is that that the toggle does not show when GPS mode is enabled, new fixed positions propagate to the map immediately and fixed position broadcast is managed by the firmware.
