### ISSUE TITLE
Channel messages not displaying on iOS18

### ISSUE THREAD

**Issue by kalinchuk** [meshtastic/Meshtastic-Apple#696]
### Firmware Version

2.2.24

### What did you do?

Go to Messages > Channels > Primary Channel. The screen is blank. This happened occasionally on iOS17 but restarting the app seemed to fix it. On iOS18 there seems to be no workaround for it. 

### Expected Behavior

Shows messages for the channel. 

### Current Behavior

Not showing messages for the channel. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Ther is no iOS 18 support at all yet

**Comment by kalinchuk** [comment]
So you close it hoping it will work on iOS18 when it's released to the public?

**Comment by thebentern** [comment]
> So you close it hoping it will work on iOS18 when it's released to the public?

It's not something we're actively tracking right now. The 18 beta just got released at WWDC and is half baked at the moment. There is no reason to spend any time on this until the dust settles.
