### ISSUE TITLE
🚀 [Feature Request]: Copy QR Code URL & Image

### ISSUE THREAD

**Issue by Hunter275** [meshtastic/Meshtastic-Apple#699]
### OS

iOS, iPadOS, macOS

### Description

Currently when sharing a QR code to Add/Replace channels, if you share the QR code it only shares the image of the QR code and not the URL the image has in it.

Default should be to share the QR code image, with the option to share the URL instead.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The share link includes the QR code image and the link, each app has its own share related code and may handle it differently.  On a Mac the link opens in the app without needing to scan
