### ISSUE TITLE
🐞 [Bug]: Node Filters Behavior Issues

### ISSUE THREAD

**Issue by RPN707** [meshtastic/Meshtastic-Apple#703]
### Firmware Version

2.3.10 (956)

### What did you do?

Using the Node Filters, some items don't filter as one would expect. Online and Favorites work. Distance and Hops Away have minor issues. Persistence of choices has been previously addressed.

### Expected Behavior

Would expect the Distance filter to filter display to show nodes "up to x miles" away.

Would expect the Hops Away filter to filter UP TO selected hops value. If not UP TO, would expect this to be multi select.
![Miles](https://github.com/meshtastic/Meshtastic-Apple/assets/173195027/17e024c4-1c1c-4421-93e0-b9a599a4339e)
![Hops](https://github.com/meshtastic/Meshtastic-Apple/assets/173195027/103fe613-d476-4f3e-9b07-4a3d91985c25)

### Current Behavior

Distance filter lets some items over the selected maximum distance show in the list.

For Hops Away filter, ANY and Direct return the same list, all nodes displayed regardless of hop count. In short, Direct is broken.

When selecting a specific Hops Away value, this is only that number. Seems like this should be UP To that number. If not, should be multiselect.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Thanks!

**Comment by garthvh** [comment]
The math on the distance filter is pretty complex, I don't have any ideas for enhancing that.

For the role filter I am adding a multi select like is on the new debug log and am working on an improved hops filter.
