### ISSUE TITLE
🐞 [Bug]: iOS 18 (beta)

### ISSUE THREAD

**Issue by soaring76** [meshtastic/Meshtastic-Apple#712]
### Firmware Version

2.3.12

### What did you do?

Messages arrive in channels overview on the iOS MeshTastic App on **iOS 18 beta,** but once you enter the channel, screen remains blank. No messages visible, nor reply prompt. 

https://github.com/meshtastic/Meshtastic-Apple/assets/47789232/be36d32c-0583-4f0e-bb1f-507b8ebad30b

![IMG_1223](https://github.com/meshtastic/Meshtastic-Apple/assets/47789232/b6ee8360-6ed2-4ef4-90bc-a1ff3c0fcb3f)
![IMG_1222](https://github.com/meshtastic/Meshtastic-Apple/assets/47789232/25052fbb-b58c-4874-ace4-03d1a079d0d8)

### Expected Behavior

Message prompt available

### Current Behavior

Message prompt not available

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Just a heads up for troubles to be expected on upcoming iOS18

Thanks for your work & time guys. Appreciated.

**Comment by garthvh** [comment]
The first couple of betas are full of bugs
