### ISSUE TITLE
App shows Hourly Duty Cycle for licensed operators 

### ISSUE THREAD

**Issue by nolith** [meshtastic/Meshtastic-Apple#714]
### Firmware Version

2.3.12

### What did you do?

Enabled hamradio licensed operator

![IMG_3768](https://github.com/meshtastic/Meshtastic-Apple/assets/78752/549dedc7-cff7-4961-9902-230625dc05df)
![IMG_3767](https://github.com/meshtastic/Meshtastic-Apple/assets/78752/9c25717d-1ea0-494a-ad6f-57dc22d78700)

### Expected Behavior

Hourly Duty Cycle warning should not be visible when configured as licensed operator.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nolith** [comment]
Using the meshtastic CLI I realized that `lora.overrideDutyCycle` was still set to `false` after enabling the ham radio mode.

I set it to `true` using the CLI but in the iOS App i still see the duty cycle warning.

**Comment by garthvh** [comment]
Closed by https://github.com/meshtastic/Meshtastic-Apple/pull/718
