### ISSUE TITLE
[Bug]: Save Disabled Channel Settings Doesn’t Work

### ISSUE THREAD

**Issue by alloploha** [meshtastic/Meshtastic-Apple#743]
### Firmware Version

2.3.13

### What did you do?

1. Open settings, select any secondary channel.
2. Change Channel Role from Secondary to Disabled.
3. Tap the Save button.

### Expected Behavior

- The new settings are sent to the device and the device is rebooted.
- The Channel Details screen is closed.
- The disabled channel is either marked as “Disabled” or disappears from the list.

### Current Behavior

- Nothing happens when the Save button is tapped.
- The Channel Settings screen remains visible.
- No changes are saved.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

OS version: iOS 17.5.1
App version: 2.3.11 (1025)

**Comment by garthvh** [comment]
fixed in 2.3.15 which is in the App Store now
