### ISSUE TITLE
🐞 [Bug]: Bluetooth Connection

### ISSUE THREAD

**Issue by JonasJ333** [meshtastic/Meshtastic-Apple#750]
### Firmware Version

2.3.11

### What did you do?

Every time I have to connect to my Meshtastic devices I now have to forget the in Bluetooth and then reconnect them afterwards.

### Expected Behavior

I should be able to reconnect to a device that I had previously connected to. 

### Current Behavior

The connection either times out and gives the ten connection attempts or the connection screen just sits at the orange “communicating with device”

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JonasJ333** [comment]
I have also tried most of the basic troubleshooting items, turning Bluetooth off and back on, phone on airplane mode and back off, deleted the app and reinstalled, turning the phone off and back on.

**Comment by garthvh** [comment]
This is a firmware issue

**Comment by JonasJ333** [comment]
![IMG_8426](https://github.com/meshtastic/Meshtastic-Apple/assets/134468644/5cd8ec85-2b66-44ec-a610-927e07b0fad9)

**Comment by garthvh** [comment]
Upgrade your firmware

**Comment by JonasJ333** [comment]
IOS App does not currently have an update in the App Store. The Meshtastic devices are all on 2.3.13 already.

**Comment by JonasJ333** [comment]
The 2.3.11 I had referenced previously is the IOS app version.
