### ISSUE TITLE
🐞 [Bug]: Direct Messages go to channel 0 by default

### ISSUE THREAD

**Issue by RustMouse** [meshtastic/Meshtastic-Apple#760]
### Firmware Version

2.2.24

### What did you do?

I changed the default channel to encrypt my location, and set the default settings (Long Fast) in channel 1.  
![IMG_9964](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/c416a288-48e9-4c22-810c-b243dd651366)
![IMG_9965](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/23f6e245-45b2-4a9e-a983-1eb98ed584ab)

### Expected Behavior

I should be able to message in the channel, identify local nodes, and send direct messages to them. The messages should go out on the channel that matches the node I'm trying to reach
![IMG_9966](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/1145b59f-31dd-48f8-92b4-d3ce0b590edc)

### Current Behavior

I can broadcast messages in the public channel, but the direct messages to known nodes fail.  When I look at the node list, the node appears on channel 1,  but when I message directly, it gives me "No Channel" error.  I've tried with two different nodes.  I can receive the messages on my device, but I cannot respond to it.  
When I look at the failed message detail, it appears to have tried to send out on channel 0, regardless of the channel the node is operating on.

![IMG_9971](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/daf33eab-0932-4cf3-8ffa-59daa0f02e30)
![IMG_9967](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/133a88a9-175d-4339-b7c6-5f5a0c002905)
![IMG_9969](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/848e9c13-6fdf-4619-9f93-bfb1ca790f9a)
![IMG_9970](https://github.com/meshtastic/Meshtastic-Apple/assets/174985627/4c8dd735-0e15-4cfa-8d0f-0dc6bec39116)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Direct messages go over the channel they share with the node in question, it is managed by the firmware

**Comment by RustMouse** [comment]
Strange - without changing anything, I can communicate with VXD3, but only after they messaged me again, though the message status still shows channel 0.
I tried the same with B2B9, and still have a "no channel" error

**Comment by GUVWAF** [comment]
The app will always leave it at 0 and then the firmware fills it in. 
It can take a while before it updates. You can delete the node from the list to speed it up, because it will request a new NodeInfo then.

**Comment by RustMouse** [comment]
Thank you,
Do you know how frequently this will update if the node is left in the list?

**Comment by GUVWAF** [comment]
By default a node sends out its NodeInfo every 3 hours.
