### ISSUE TITLE
🚀 [Feature Request]: Neighbor Info support in the IOS UI

### ISSUE THREAD

**Issue by tcivie** [meshtastic/Meshtastic-Apple#762]
### OS

iOS

### Description

Hey, we are using in our local comunity the Neighbor Info to display a node graph and have a complete connection map with other nodes.

All the nodes that we can connect to with Android/Web are configured to publish Neighbor Info data. But it looks like in the IOS this option is not available and in the official documentation it also states that there is no current support for that.

I would really appreciate it if someone could add this configuration to the UI.

https://meshtastic.org/docs/configuration/module/neighbor-info/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
I have some ideas, won't add the config until I have a UX as it takes a bunch of airtime.  Not adding anything new that is going to use more airtime until after burning man is over.
