### ISSUE TITLE
🚀 [Feature Request]: an empty channel name should match the modem preset

### ISSUE THREAD

**Issue by nolith** [meshtastic/Meshtastic-Apple#767]
### OS

iOS, iPadOS, macOS

### Description

When you don't set the chanel name, ie the default channel, the app will show it as "Primary" if primary, or "Channel N" if secondary.

But folks talks about the default channel as the modem preset name i.e. LongFast or MedFast. Moreover both the MQTT topic for a channel and the default channel OLED display is the channel name, but when empty it utilises LongFast/MedFast/...

I think that using the same name in the UI will give a better experience, especially for those folks not using it as the primary channel.

Thank you for your amazing work 🚀 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ljmckay** [comment]
Is there any reason why is this closed/notplanned? It's causing major headaches between Android, Apple, and CLI users who can't agree on what the channel name actually is because it's hidden from iOS users. I'd even consider this to be a major usability bug and not an enhancement request.
