### ISSUE TITLE
iOS18 channel messages not accessible 

### ISSUE THREAD

**Issue by mikey1963** [meshtastic/Meshtastic-Apple#783]
### Firmware Version

2.3.13

### What did you do?

The version of iOS app 2.3.15 and iOS18 seems to show a fault in that when selecting a channel to send a message on or to read a message, you just get a blank screen with no messages and no edit window to write any messages.  It was ok before I upgraded to iOS 18 so it could a fault in the beta or it could a feature of the new iOS.

### Expected Behavior

I expected to see an edit window and some sent messages

### Current Behavior

Blank screen as per attached screen shot

![IMG_2046](https://github.com/meshtastic/Meshtastic-Apple/assets/30376528/c4e50ba5-f7cb-4e1e-8731-7fa348b6111e)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I am only reporting it in case it’s a new iOS feature rather than an iOS fault.

**Comment by garthvh** [comment]
There is no ios18 SUPPORT YET
