### ISSUE TITLE
🚀 [Feature Request]: Mapview improvement

### ISSUE THREAD

**Issue by denis-ev** [meshtastic/Meshtastic-Apple#796]
### OS

iOS

### Description

I am uncertain if this is a bug or an intended feature. I'm currently working with two nodes as I start learning more about LoRa and Meshtastic. In the main channel, I’ve set the location to an approximate distance of a few kilometers, which is what I want everyone to see. However, in a different encrypted channel with my other node, I’ve set the location to be exact.

On the map or elsewhere in the Meshtastic app, I can't find the exact location for my other node, which should be shared. Therefore, my request is to either:

1. Enable prioritization of channels that provide the closest location,
2. Find the channel with the most precise location, or
3. Allow users to choose the channel for the map view.

Thank you.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Positions are sent mostly over the primary channel, they can be requested on secondary channels.
