### ISSUE TITLE
Primary channel UI bug

### ISSUE THREAD

**Issue by jrjdavidson** [meshtastic/Meshtastic-Apple#809]
### Firmware Version

2.3.17

### What did you do?

Open channel UI and nothing appears. Direct messaging appears in affected.

Note I recently updated to iOS 18

https://github.com/user-attachments/assets/57027a3a-01c7-44b3-8587-4a8e2d091c0c

### Expected Behavior

I would expect to be able to see the message UI that I see in direct messages, but instead get a blank screen

### Current Behavior

White screen.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
iOS
