### ISSUE TITLE
🚀 [Feature Request]: range test packets should be in a separate "tab" like device or environment metrics

### ISSUE THREAD

**Issue by akohlsmith** [meshtastic/Meshtastic-Apple#812]
### OS

iOS, iPadOS, macOS

### Description

In order to make Range Test more useful, the app should be displaying them in a graph/table like what is already done for device or environmental metrics. Off the top of my head, I'd recommend a scatter graph (similar to device metrics airtime and channel utilization) -- Graph data would be SNR and RSSI and perhaps a missed sequence number (or series of missed sequence numbers) could be represented by a red dot/line at y=0 to help draw attention to missed data. CSV export would be helpful as well, of course.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This feature is kind of a mess, not sure it is worth the effort
