### ISSUE TITLE
🐞 [Bug]: OSX TestFlight app has no channels

### ISSUE THREAD

**Issue by akohlsmith** [meshtastic/Meshtastic-Apple#813]
### Firmware Version

2.4.0.1093

### What did you do?

Connected to my t-echo (firmware 2.3.15) as usual, went to the Messages tab at the bottom of the screen and the usual "Channels" and "Direct Messages" tabs are on the left side. if I click on "Channels" nothing happens - there are no channels to be displayed. Clicking on "Direct Messages" brings up a list of all nodes in the nodedb which is expected.

### Expected Behavior

The Channels tab should show the configured channels. In my case the default channel, the admin channel and the gpio channel. None show up.

### Current Behavior

No channels appear in the channel list. Direct Messages list looks correct.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by vvuk** [comment]
This is the case with the latest public version in the App Store as well (2.3.17 (1078)). iOS 18 Public Beta, in case it's an issue there.
