### ISSUE TITLE
🐞 [Bug]: Keyboard obscures latest messages in channel view

### ISSUE THREAD

**Issue by jasonfish** [meshtastic/Meshtastic-Apple#819]
### Firmware Version

2.3.13.83f5ba0

### What did you do?

Receive multiple messages, open message thread to read, tap text entry box to reply. Keyboard appears, obscuring the last 2-3 messages. Attempting to scroll the view to reveal the latest messages hides the keyboard. If more messages arrive while you're typing, you must close the keyboard to "catch up" on the conversation, then resume typing.

iPhone 15 Pro Max, iOS 17.5.1

![IMG_1046 Medium](https://github.com/user-attachments/assets/6e513af1-631d-4e42-87fc-04efd421175d)
![IMG_1047 Medium](https://github.com/user-attachments/assets/a38de1fd-3f1c-4a0f-94dc-d3b2fb5f4356)

### Expected Behavior

It should be possible to view/read/reference the latest messages as you type your reply, message view should resize to accommodate keyboard.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
No real easy way to manage this right now, may be easier after iOS 16 is dropped
