### ISSUE TITLE
🐞 [Bug]: Battery Information is not updated in the list view, but is updated in the detail view.

### ISSUE THREAD

**Issue by 72A12F4E** [meshtastic/Meshtastic-Apple#830]
### Firmware Version

2.4.0

### What did you do?

Charging a node currently. Battery info is not being updated in the list view, but is being updated in the detail view. 

### Expected Behavior

These two values should be in-sync

### Current Behavior

![Screenshot 2024-08-01 at 11 24 18-1](https://github.com/user-attachments/assets/c898fc47-00ad-4ed6-910b-1a8d2c656a46)
![Screenshot 2024-08-01 at 11 24 15](https://github.com/user-attachments/assets/9331d89d-59ca-4940-a53c-eb822093814e)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
fixed in the 2.5 App Store release, removed a bunch of view layers
