### ISSUE TITLE
🚀 [Feature Request]: Navigate to the connected radio's node info or device metrics log from the bluetooth screen

### ISSUE THREAD

**Issue by gabek** [meshtastic/Meshtastic-Apple#836]
### OS

iOS

### Description

Currently, unless I'm missing something obvious, in order to get to the device details of the currently connected radio, I have to navigate to the list of nodes, find my node, select it, and then go to the device metrics log.

I would like to be able to view the device metrics log directly from the connected radio bluetooth screen.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Lolagatorade** [comment]
Yeah same here. 


Also on nodes list latest update broke the stat for battery does not show actually if it is charging powered or on battery ect. Not as expected behavior. It just says the voltage increased but not powered even tho it is...
