### ISSUE TITLE
MQTT does not send to everyone subscribed. 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#850]
### Firmware Version

2.4.1

### What did you do?

Recently, I got MQTT working, which was surprisingly buggy, and even with the same exact configurations would refuse to send.  Now (functional), it acknowledges every message but this issue is more intermittent and extensive .

Now that messages actually get through to a recipient the main issue is that not everybody subscribed to the topic can actually view the messages sent

At times I am able to see something another user may not. Or vice versa. Take note that the root topic is not very large in terms of active users.

### Expected Behavior

If a message is sent, it is expected to be received by everybody that is currently viewing and subscribe to the topic. As in how MQTT should function with topics ect. 

### Current Behavior

A message sent is not guaranteed to be seen by everybody subscribe to a root topic. Attached is an example where I reply to something somebody said, but one user is not on the same page and was confused because he saw my reply but not the context
![IMG_7540](https://github.com/user-attachments/assets/50c7139e-e0a6-4dd1-be19-e0ca7ef0204c)
![IMG_7541](https://github.com/user-attachments/assets/2389ae11-ebee-4715-a359-77b692d1e7cb)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Lolagatorade** [comment]
Another example of a user replying to a message that was never received...

![image](https://github.com/user-attachments/assets/1a24eb3b-5d73-47ff-8bf1-3aa3126b1f2b)

**Comment by garthvh** [comment]
On the default long fast channel the public MQTT server is zero hopped since July 15, these messages are no longer forwarded via lora.
