### ISSUE TITLE
🐞 [Bug]: LED Heartbeat setting unchangeable on Heltec V3

### ISSUE THREAD

**Issue by fiveangle** [meshtastic/Meshtastic-Apple#851]
### Firmware Version

2.4.1.394e0e1

### What did you do?

Attempt to change the state of LED Heartbeat via changing toggle at:

Settings > Device > LED Heartbeat

Save button does not go active, so change cannot be applied.

Additional troubleshooting:

1. Make above "LED Heartbeat" state change and observe "Save" button not go active
2. On same "Device Config" page, change "Device Role" from "Client" to "Client Mute"
3. Observe "Save" button go active
4. Tap "Save" and apply setting
5. After reboot, observe Heartbeat LED and Device Role state both have changed and hardware LED reacts as expected

### Expected Behavior

Expected "Save" button should go active, allowing to apply the changed setting

### Current Behavior

Expected "Save" button does not go active, disallowing to apply the changed setting

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is on iPadOS 17.5.1, Meshtastic app version 2.4.1 (1121), Heltec V3 hw

**Comment by garthvh** [comment]
fixed in the 2.5 App Store release
