### ISSUE TITLE
Widgets for home screen and lock screen 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#852]
### OS

iOS, iPadOS, macOS

### Description

Would be nice and it’s within capabilities of an application on Apple to have widgets and populate information. Similar to what’s in a meshtastic oled screen or specific datapoints like tempreture, pressure ect from a specified source local or remote ect. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by squidjuice** [comment]
I'd like to see this as well def on Lock Screen
