### ISSUE TITLE
🐞 [Bug]: Environment Telemetry over connected node's PhoneAPI packets does not load

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Apple#858]
### Firmware Version

Yes

### What did you do?

Opened node details and witnessed empty / disabled Environment Telemetry Log

### Expected Behavior

Expected to see packets and charts

### Current Behavior

No candy

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This is working, even on the 1 minute interval for the local node use a BME 680 on a 4631 on a RAK.  I did get log errors and no data on slots A and B

**Comment by garthvh** [comment]
The different database versions is TestFlight are probably the source of this
