### ISSUE TITLE
🐞 [Bug]: Battery percentage inconsistent

### ISSUE THREAD

**Issue by purge98** [meshtastic/Meshtastic-Apple#860]
### Firmware Version

2.4.1

### What did you do?

Checked Device Metrics Log and it shows different battery percentages for the same voltage. 

### Expected Behavior

A particular voltage should always show the same percentage.

### Current Behavior

App shows different battery percentages for the same voltage

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

![IMG_6146](https://github.com/user-attachments/assets/f2666b13-6e9c-4901-ac91-b72085805183)
![IMG_6145](https://github.com/user-attachments/assets/638f9d62-09ed-4947-8ceb-12514b143341)
![IMG_6144](https://github.com/user-attachments/assets/4c1c35e5-0c5b-4b25-8bbc-982529ee4702)

**Comment by purge98** [comment]
Thanks for closing it BUT why does Volts 3.51 show 18% and 30%? Doesn’t correlate.

**Comment by garthvh** [comment]
There is already an open issue, please check before opening another one
