### ISSUE TITLE
🐞 [Bug]: Frequency Override

### ISSUE THREAD

**Issue by Camousse88** [meshtastic/Meshtastic-Apple#861]
### Firmware Version

2.4.1

### What did you do?

On iOS, when setting a frequency with four digits after the decimal point, such as 869.4625 (Gaulix network in France), the application rounds to three digits after the decimal, 869.463.
This results in a frequency offset.

### Expected Behavior

Get four digits after the decimal point.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Camousse88** [comment]
![IMG_4436](https://github.com/user-attachments/assets/f894095f-0875-4455-a2da-1f6de76d2387)
![IMG_4437](https://github.com/user-attachments/assets/58214a5a-9454-436f-b744-a74d0114520d)

**Comment by garthvh** [comment]
There is just a float value be passed around in the app, nothing is being modified converted or rounded at all by the app.

**Comment by Camousse88** [comment]
It’s not a bug it’s a feature. 🙂

More seriously. It’s not clear; rounding to 4 decimals would be more readable.

Too bad

**Comment by garthvh** [comment]
There is a number formatter on there, I will see if maybe that has a default decimal precision
