### ISSUE TITLE
Battery telemetry values seem incorrect in table

### ISSUE THREAD

**Issue by jrjdavidson** [meshtastic/Meshtastic-Apple#868]
### Firmware Version

2.4.1

### What did you do?

In the iOS app, go to the nodes tab. Select a node on the network and then look up the device metrics logs.

The battery percentage values seem jumbled in the table below, but the graph appears to be correctly displaying the values.

![IMG_0847](https://github.com/user-attachments/assets/a86f79e4-45c9-407e-bd33-50a1e723388f)

### Expected Behavior

On the line in the screenshot, I would expect the value to display ~100%

### Current Behavior

The battery percentage value displays 60%

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nbgibson** [comment]
I suspect that the app may be at the mercy of what the board/firmware is telling it. Heltec's ESP32 boards appear to be a bit flaky in this area, no idea what the situation is elsewhere.

I have similar issues where the board will incorrectly report charge levels or state (plugged in, not plugged in, ect) that are usually either cleared up via restarting the node/app or just waiting for a re-polling of the state.
