### ISSUE TITLE
Sensor graph missing time stamp after reboot

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#874]
### Firmware Version

2.4.3

### What did you do?

After reboot it starts populating datapoints. When you look at the sensor data, there is no graph. The timestamps are missing for sometime until they populate. Eventually it works but it takes too long. The poll rate for the sensor is set to 1 minute.  

### Expected Behavior

Tike stamp should populate after a reboot basically instantly so the graph can graph over time 
![IMG_7730](https://github.com/user-attachments/assets/65979bdc-030f-40aa-8791-ab2a6c43a184)

### Current Behavior

As mentioned the graph does not populate because of missing time stamps 

attached is an example of 223x my node and an example of functional node. 

![IMG_7729](https://github.com/user-attachments/assets/5e76e6f6-0121-444c-815c-4317f19dbdb5)
![Uploading IMG_7731.png…]()

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Time is managed entirely by the firmware, the app show the time it was given

**Comment by Lolagatorade** [comment]
> Time is managed entirely by the firmware, the app show the time it was given

My bad forgot to close it. They did a hot fix for the firmware a day or two ago.
