### ISSUE TITLE
IAQ colored dots off center when looking as column 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#875]
### Firmware Version

2.4.3

### What did you do?

Title explains it 

### Expected Behavior

Dots should line up 

### Current Behavior

Dots don’t 
![IMG_7734](https://github.com/user-attachments/assets/ab67f4e8-d6ca-49bb-82e2-e3b13ec1d9e0)
![IMG_7733](https://github.com/user-attachments/assets/18cb5d54-e091-405d-b71b-e153966569e0) up 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Lolagatorade** [comment]
Placing them to the left of the IAQ might solve the issue it's probably just the numbers being slightly smaller or larger and shifting it over

**Comment by garthvh** [comment]
The grids are being replaced for all the logs
