### ISSUE TITLE
🚀 [Feature Request]: Implement fixed position input (and duty cycle override) on apple devices

### ISSUE THREAD

**Issue by OE5DRO** [meshtastic/Meshtastic-Apple#876]
### OS

iOS

### Description

it would be very nice to have the possibility to set gps koordinates as fixed position as on adroid app. sometimes the fixed position gets lost by no reason and i could not be found out with apple device. maybe DC override switch would also be nice for short testing something. tnx in advance
( OTA update please :)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
fixed position is set from your phone location, you can override duty cycle in licensed user mode.
