### ISSUE TITLE
🚀 [Feature Request]: Update all Hardware images

### ISSUE THREAD

**Issue by RCGV1** [meshtastic/Meshtastic-Apple#877]
### OS

iOS, iPadOS, macOS

### Description

Add more images of hardware to the app. If the device ships with a case then use the image of it with the case, if the device is a development board then use an image of the board (TBeam and Rak 4631)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
We are going to manage these images with vendors via Meshtastic solutions, until then we are going to leave the images as is
