### ISSUE TITLE
🚀 [Feature Request]: Implement IP Connection

### ISSUE THREAD

**Issue by OE5DRO** [meshtastic/Meshtastic-Apple#879]
### OS

iOS

### Description

please implement IP connection like in android app. this would help to stay connected when BT signal is weak.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
Duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/296

Has a bounty with $0 raised so priority is real low.
