### ISSUE TITLE
Small typo issue easy fix

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#885]
### Firmware Version

2.5.0

### What did you do?

Typo on a word 
![IMG_7853](https://github.com/user-attachments/assets/bc27cc4c-7457-482c-a8d5-8863f82b2c39)

### Expected Behavior

Requires 

### Current Behavior

Reguires 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by KarmaJaneK** [comment]
I’d like to work on this issue, can I be assigned?

**Comment by Lolagatorade** [comment]
> I’d like to work on this issue, can I be assigned?

I think it's already taken care of / getting taken care of
