### ISSUE TITLE
Timestamps and delta 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#896]
### OS

iOS, iPadOS, macOS

### Description

As an optional setting for messages, it would be nice due to how disorganized at times messages arrive to have a timestamp system with a Delta between the time received and time actually sent from sender

not sure if this is possible because I do not know if the meta-data also includes the time that it was sent from the sender as I can only see a message details the time received on my end either way this would be a very nice feature theoretically would not include any changes to the firmware because it’s just organizing meta data.

![IMG_7939](https://github.com/user-attachments/assets/4e70b14f-7b5f-4c38-98da-61e79579ed43)

Mockup of a UI 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SystemBurm** [comment]
Nice that'll be a good idea
