### ISSUE TITLE
Local Bluetooth node showing hop 

### ISSUE THREAD

**Issue by Lolagatorade** [meshtastic/Meshtastic-Apple#910]
### Firmware Version

2.5.0

### What did you do?

This bug report is regarding a nonsensical issue where the directly connected node through Bluetooth is showing a hop where it is nonsensical since it is a direct connection

### Expected Behavior

Direct connection 

### Current Behavior

Showing hops when it’s direct connection. If it is a new feature, then it should be described. If not, it makes no sense to show hops. 
![IMG_8003](https://github.com/user-attachments/assets/3a6623c6-19b7-4165-8820-c51c793dc5cc)
![IMG_8002](https://github.com/user-attachments/assets/e81b104f-436e-4ead-b946-9f15aaa87390)
![IMG_8004](https://github.com/user-attachments/assets/bc6a0a90-202b-480e-9eb3-e4f2c19de07e)
![IMG_8005](https://github.com/user-attachments/assets/9a1a732c-5aa1-4301-8ca6-3ec532b09279)
 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
This needs to be fixed in the firmware
