### ISSUE TITLE
🚀 [Feature Request]: Navigate to a specific node within the "Mesh Map" UI

### ISSUE THREAD

**Issue by powersjcb** [meshtastic/Meshtastic-Apple#915]
### OS

iOS

### Description

Navigate to a specific node within the "Mesh Map" UI

# Problem statement
When using this app in a social context, it's often quite useful to answer the question, "Where is my friend and who are they with?"

"Mesh Map" is currently a not-great tool for finding people unless they are relatively far from any other nodes on the map. (only the bottom-left node name is displayed when of 2 or more nodes are near each-other - see screenshots)

This means that to find someone and see who they are with you have to follow this process:
* process 1: lots of pinch zooming on a cluttered GPS map
  * launch "Mesh Map" view
    * can I see them?
      * yes: you found them - usually only happens if they are alone
      * no: their name is hidden in a cluster of node icons
        * zoom/out into each group individually and see if they are there
* process 2: cross reference location from "Node Map"
  * look for where the person "Nodes" -> "Node Detail" -> "Logs" -> "Node Map" that launches a UI to show the location of a node on a map. This UI only shows the currently selected node's location.
  * open "Mesh Map" and find find the location from the "Node Map"

| Mesh Map Screen (all users, but no search) | Node Map Screen (only shows one user) |
|-------------------|--------------------|
|<img width="188" alt="image" src="https://github.com/user-attachments/assets/25541973-f90a-4829-bf29-c69399775e4f">|<img width="194" alt="image" src="https://github.com/user-attachments/assets/bf25487e-f793-4c29-aa6d-9a8f1daac382">|

# Proposed improvement

### option 1: deep link to "Mesh Map"

option 1a: Add a button to "View in Mesh Map" on the "Node Details" screen. This button will navigate to the "Mesh Map" screen and center the location on the Node's current location.

option 1b: Add a button to "View in Mesh Map" on the "Direct Messages" screen. This button will navigate to the "Mesh Map" screen and center the location on that Node's current location.

Pros:
* trivial UI changes

Cons:
* harder to find feature - would be nice to have this context in "Mesh Map UI"
* some overlap/confusion with the single "Node Map" UI vs the deep linked "Mesh Map" UI
* TBD of complexity in deep linking into the "Mesh Map" screen (need feedback to see if this is a problem)

### option 2: Add a Search to the Mesh Map screen that allows users to set map focus. (a-la Google Maps) Clicking the search box without any content shows an autocomplete list containing favorited nodes.

Pros:
* better feature discovery

Cons:
* complexity of new UI elements

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

I generally get the sense that options 1a/1b would be easiest, but I would love feedback about my assumptions that deep-linking/routing between different sections of the app will be feasible since I haven't looked at this codebase yet.

**Comment by mertensm72** [comment]
+1 I would like this too
