### ISSUE TITLE
🐞 [Bug]: keyboard covers bottom messages on direct message chat view

### ISSUE THREAD

**Issue by spydercs** [meshtastic/Meshtastic-Apple#917]
### Firmware Version

2.5.0

### What did you do?

Open a direct message to a node and hit the text field to type a message.

### Expected Behavior

The keyboard pops up and the bottom (newest) messages are still visible. 

### Current Behavior

The keyboard slides up and blocks the view of the most recent messages at the bottom.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

When testing this I tried it in the channel chat to see if it happened. The keyboard popped up and the messages moved up so I could see them however the bottom message was partially cut off. After opening and closing the channel chat a few times the same issue above started occurring in the channel chat as well. Restarting the app didn't fix the problem.

I am using an iPhone 13 mini with iOS 17.6.1.

**Comment by mertensm72** [comment]
Using BBS stumbles over this issue. When direct messaging with the TC2-BBS-Mesh client the keyboard closes and opens and jumps up and down...
