### ISSUE TITLE
🚀 [Feature Request]: allow users to hide node "possible locations" ranges on MeshMap

### ISSUE THREAD

**Issue by powersjcb** [meshtastic/Meshtastic-Apple#920]
### OS

iOS

### Description

**Problem**

There's a handful of users in my area that have very large position uncertainty configured. These are causing 1-10 mi circles to appear on the map for each of them.

<img width="231" alt="image" src="https://github.com/user-attachments/assets/0c2f4934-e7e1-445b-99cc-261598f36ab5">

**Proposed Solution**

* Add a new MeshMap setting to disable range circles
* Add a new position uncertainty value to the node detail view on MeshMap.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Perhaps in the future, deep linking to a node could launch the map UI and center on that node. With the node selected, it enables the uncertainty distance circle for just that node and sets the minimum zoom distance to be ~2-3x the size of that circle. (so the user is made aware if the position is not accurate)

**Comment by powersjcb** [comment]
<img width="369" alt="image" src="https://github.com/user-attachments/assets/48036c12-093c-47d9-a1f6-f4fa394a21b3">

**Comment by powersjcb** [comment]
wow, someone on reddit separately posted a question about what these circles are about a week ago.

They included a nearly nearly identical screenshot of the issue we are seeing on the SLC area map. 

https://www.reddit.com/r/meshtastic/comments/1f5xit0/what_do_the_rings_mean_on_the_meshtastic_app_map/

**Comment by powersjcb** [comment]
splitting out this ticket to help users understand these circles when they are shown. https://github.com/meshtastic/Meshtastic-Apple/issues/924

**Comment by garthvh** [comment]
Lines seems great, hiding imprecise locations does not match the direction the project is going.
