### ISSUE TITLE
🐞 [Bug]: GPS Coordinates slightly off in iOS and macOS app for Heltec T114

### ISSUE THREAD

**Issue by jayseeee** [meshtastic/Meshtastic-Apple#940]
### Firmware Version

2.5.0

### What did you do?

When using the matching L76K GPS the coordinates show up correctly on the device LCD. In the iOS and macOS app the coordinates are off by a several hundred meters in a non random, deterministic way. This behavior also occurs when "Dilution of precision (DOT)" is switched off.

### Expected Behavior

The GPS coordinates shown on the LCD display of the device should match the coordinates shown within the app (location on the map).

### Current Behavior

There is an offset between the coordinates shown on the LCD display versus the coordinates shown in the app on the map.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The offset is also present when using the 2.4.3 version of the firmware. 

The used macOS app version is 2.5.4
The used iOS app version is 2.5.5
The offset is the same when comparing the macOS and the iOS version of the app.

The web client on the other hand shows the correct location.

In the serial monitor I can verify that the correct location is transferred to the app.

**Comment by garthvh** [comment]
There is no expectation that these will match.
