### ISSUE TITLE
🐞 [Bug]: After opening notification of 'new node has been discovered' the new node will be shown every time the node button is pressed.

### ISSUE THREAD

**Issue by spydercs** [meshtastic/Meshtastic-Apple#950]
### Firmware Version

2.5.2

### What did you do?

A new node notification came up on my screen and I pressed it. The new node was displayed. After pressing the back button to show all nodes, navigating to another tab (like messages), then selecting the node view again it again displayed the new node. This continued until I restarted the app.

### Expected Behavior

When navigating away from the node view and selecting it again I would expect that the full list of nodes would be displayed. Especially after using the back button

### Current Behavior

The node view continues to show the same node every time the node  button is pressed.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

iOS version 18.0

**Comment by mertensm72** [comment]
+1 same here
