### ISSUE TITLE
🚀 [Feature Request]: Add Ad Hoc Ping to BLE Connected Node's Long Press Actions

### ISSUE THREAD

**Issue by Coopersmith-24601** [meshtastic/Meshtastic-Apple#951]
### OS

iOS, iPadOS, macOS

### Description

There are now several devices being manufactured without hardware to invoke Ad Hoc Ping; Heltec Capsule, T1000-e, etc.

I would very much like to be able to add this to the menu of actions which can be performed by long pressing the node if connected to via BLE.  This would facilitate the node showing up on other Mesh connected nodes if those nodes' node db have been wiped during firmware updates.

![IMG_1580](https://github.com/user-attachments/assets/4ad41bf8-4103-4f1a-8872-43d55dbd2d6b)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
https://github.com/meshtastic/Meshtastic-Android/issues/1099
