### ISSUE TITLE
🚀 [Feature Request]: Support for M5Stack CoreS3 board

### ISSUE THREAD

**Issue by lboue** [meshtastic/Meshtastic-Apple#959]
### OS

iOS

### Description

Add support for M5Stack CoreS3 board

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Related to PR #958.

![image](https://github.com/user-attachments/assets/df26f6ad-864c-4939-ba87-585a9f00e5ad)

**Comment by garthvh** [comment]
Has to be updated in the protobufs, I don think your name change in the protos will work.

**Comment by lboue** [comment]
@garthvh It is define here:https://github.com/meshtastic/protobufs/blob/c9ae7fd478bffe5f954b30de6cb140821fe9ff52/meshtastic/mesh.proto#L637
