### ISSUE TITLE
🐞 [Bug]: Messages disappearing after disconnecting from and reconnecting to node

### ISSUE THREAD

**Issue by jrodh13** [meshtastic/Meshtastic-Apple#963]
### Firmware Version

2.5.4

### What did you do?

I have four WisMesh Pocket nodes all with firmware version 2.5.4. Using the IOS Meshtastic app version 2.5.8. I have messages displayed in the Meshtastic IOS app. I disconnect from that node and connect to another node. Then I disconnect from that new node and reconnect to the original node (the one that had the messages). Upon reconnecting the messages are gone in the Meshtastic IOS app, but the last message received by the node is still displayed on the node.

### Expected Behavior

The last messages should still be present in the Meshtastic app (at least that's what I would think). I would expect the app to query the node for messages and redisplay them.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by garthvh** [comment]
The user is the node, there is no support for blended messages with multiple users
