### ISSUE TITLE
🐞 [Bug]: MacOS client always jumps back to bluetooth screen when some buttons are pressed

### ISSUE THREAD

**Issue by ye-no** [meshtastic/Meshtastic-Apple#979]
### Firmware Version

2.5.9

### What did you do?

Clicked on messages, then channels.

### Expected Behavior

should show the channels page

### Current Behavior

brings back to bluetooth page

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by caveman99** [comment]
for context: this is a bug in MacOS Sequoia and can not be fixed in the app.
