### ISSUE TITLE
🐞 [Bug]: Can't transmit if declared a Licensed Operator

### ISSUE THREAD

**Issue by AlanTheBeast** [meshtastic/Meshtastic-Apple#988]
### Firmware Version

2.5.6

### What did you do?

**CASE** Canada - 433MHz - licensed amateur - T-Beam
- have to set Region to "Europe 433MHz" - there is no such setting for Canada, US, North America
- have set user name to my radio license
- have to turn OFF "Licensed Operator" - or the device will not transmit
- Key is set to Empty or to "AQ=="

### Expected Behavior

Message should go

### Current Behavior

Try to send message.  Get : ["Encrypted Send Failed"]

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Confusing that there is no "Canada 433MHz" region (or North America - would be appropriate)

**Comment by garthvh** [comment]
This is fixed in the latest alpha firmware
