### ISSUE TITLE
🚀 [Feature Request]: Canada (or US or North America) 433MHz Region

### ISSUE THREAD

**Issue by AlanTheBeast** [meshtastic/Meshtastic-Apple#989]
### OS

iOS

### Description

All OS.  Currently there is no "US" or "Canada" 433MHz region. (Amateur Radio Licensed).
For 433MHz radio users, this is confusing, as a "US" selection with such a radio does not work. (will not transmit - T-Beam).
Not clear to me that this is also limiting power output - I'll test forthwith.

### Participation

- [ ] I am willing to pay to sponsor this feature.
- [X] I am willing to submit a pull request for this feature.

**Comment by garthvh** [comment]
Regions are managed in the firmware, use Ukraine 433.
