### ISSUE TITLE
🚀 [Feature Request]: Show how many times a message has been Acknowledged

### ISSUE THREAD

**Issue by mdesmedt** [meshtastic/Meshtastic-Apple#990]
### OS

iOS

### Description

I'm not sure if this is possible without a firmware change, but it I think it would be useful (for all clients, not just iOS) to show how many times a sent message has been acknowledged.

For example, if I have another node active in the house, I might immediately get an ACK from my own node but I might not get an indication of whether it has been "usefully" received by other nodes further away.

Seeing something like "Acknowledged (4)" instead of "Acknowledged" could give users an indication that the packet went out to more than just a single node.

### Participation

- [ ] I am willing to pay to sponsor this feature.
- [ ] I am willing to submit a pull request for this feature.

**Comment by GUVWAF** [comment]
Unfortunately that's not really possible. It can be indeed you receive multiple 0-hop acknowledgments (implicit ACKs as the firmware calls them) if multiple nodes try to rebroadcast when they can't hear each other. However, for broadcast messages, there are no real ACKs going over multiple hops, and we don't even know who sends the implicit ACK.
